import { TRANSLATION_OVERRIDES } from "./translation-overrides.js";
import { getReviewRecord, isReviewCurrent } from "./translation-review.js";

export const REQUIRED_UI_KEYS = [
  "eyebrow", "heroTitle", "heroEmphasis", "heroBody", "neverStored",
  "languages", "notDiagnosis", "language", "explain", "drop", "uploadHint",
  "findings", "meaning", "questions", "lifestyle", "copyQuestions", "savePdf",
  "changeLanguage", "newReport", "recentReports", "clearHistory", "noReports",
  "disclaimerTitle", "disclaimerBody", "reading", "translating", "copied",
  "invalidFiles", "uploadFirst", "tooManyPages", "payloadTooLarge", "remove",
  "page", "reference", "report", "normal", "low", "high", "borderline", "critical",
  "reviewTitle", "reviewIntro", "confidence", "highConfidence", "mediumConfidence",
  "lowConfidence", "confirmValues", "cancelReview", "uncertainValues", "fieldTest",
  "fieldValue", "fieldUnit", "overview", "nextSteps", "chooseLanguage", "close",
  "all", "outsideRange", "uncertain", "confirmed", "summary", "attention", "trends",
  "noTrends", "date", "glossary", "readAloud", "stopReading", "speechUnavailable",
  "doctorSummary", "followUpReminder", "reminderDate", "addToCalendar", "selectDate",
  "rangePosition", "trendTable", "visitToolkit", "requestFailed", "uninterpreted",
  "expandAll", "collapseAll", "needsAttention", "audioConsent", "audioDisclosure",
  "audioLoading", "playAudio", "pauseAudio", "restartAudio", "tooManyFindings",
  "analysisTimeout", "processingConsentTitle", "processingConsentBody",
  "processingConsentAccept", "processingConsentDecline", "processingConsentManage",
  "processingConsentDeclined", "beta"
];

const en = {
  eyebrow: "Private · No sign-up", heroTitle: "Your medical report,", heroEmphasis: "finally in plain words.",
  heroBody: "Upload a lab report or prescription. Lumen explains every value and prepares questions for your doctor.",
  neverStored: "Never stored", languages: "languages", notDiagnosis: "Not a diagnosis — a translation", language: "Language",
  explain: "Explain my report", drop: "Drop your report here", uploadHint: "Lab report, prescription, or discharge summary · JPG or PNG · up to 5 pages",
  findings: "Your numbers", meaning: "What this means", questions: "Ask your doctor", lifestyle: "General wellbeing notes",
  copyQuestions: "Copy questions", savePdf: "Save as PDF", changeLanguage: "Change language", newReport: "New report",
  recentReports: "Recent reports", clearHistory: "Clear history", noReports: "No saved reports yet.",
  disclaimerTitle: "Lumen is not a doctor.", disclaimerBody: "It explains medical documents to support conversations with healthcare professionals. It does not diagnose, treat, or replace medical advice. Always consult a qualified clinician. Images are sent to the selected AI provider for analysis and are not stored on our servers.",
  reading: "Reading your report…", translating: "Translating…", copied: "✓ Copied", invalidFiles: "Please upload JPG or PNG images.",
  uploadFirst: "Upload a report first.", tooManyPages: "You can upload up to 5 pages.", payloadTooLarge: "The pages are too large. Remove a page or use clearer, smaller images.",
  remove: "Remove", page: "Page", reference: "ref", report: "Report", normal: "normal", low: "low", high: "high", borderline: "borderline", critical: "critical"
};

const translations = {
  hi: {
    eyebrow: "निजी · साइन-अप नहीं", heroTitle: "आपकी मेडिकल रिपोर्ट,", heroEmphasis: "अब आसान शब्दों में।", heroBody: "लैब रिपोर्ट या पर्चा अपलोड करें। Lumen हर मान समझाता है और डॉक्टर से पूछने के प्रश्न तैयार करता है।", neverStored: "कभी संग्रहीत नहीं", languages: "भाषाएँ", notDiagnosis: "निदान नहीं — केवल सरल व्याख्या", language: "भाषा", explain: "मेरी रिपोर्ट समझाएँ", drop: "अपनी रिपोर्ट यहाँ डालें", uploadHint: "लैब रिपोर्ट, पर्चा या डिस्चार्ज सारांश · JPG या PNG · अधिकतम 5 पृष्ठ", findings: "आपके परिणाम", meaning: "इसका क्या अर्थ है", questions: "डॉक्टर से पूछें", lifestyle: "सामान्य स्वास्थ्य सुझाव", copyQuestions: "प्रश्न कॉपी करें", savePdf: "PDF सहेजें", changeLanguage: "भाषा बदलें", newReport: "नई रिपोर्ट", recentReports: "हाल की रिपोर्टें", clearHistory: "इतिहास मिटाएँ", noReports: "अभी कोई रिपोर्ट सहेजी नहीं गई।", disclaimerTitle: "Lumen डॉक्टर नहीं है।", disclaimerBody: "यह स्वास्थ्यकर्मी से बेहतर बातचीत के लिए मेडिकल दस्तावेज़ समझाता है। यह निदान, उपचार या चिकित्सा सलाह का विकल्प नहीं है। हमेशा योग्य डॉक्टर से सलाह लें। चित्र विश्लेषण के लिए चुने गए AI प्रदाता को भेजे जाते हैं और हमारे सर्वर पर संग्रहीत नहीं होते।", reading: "रिपोर्ट पढ़ी जा रही है…", translating: "अनुवाद हो रहा है…", copied: "✓ कॉपी किया", invalidFiles: "कृपया JPG या PNG चित्र अपलोड करें।", uploadFirst: "पहले रिपोर्ट अपलोड करें।", tooManyPages: "आप अधिकतम 5 पृष्ठ अपलोड कर सकते हैं।", payloadTooLarge: "पृष्ठ बहुत बड़े हैं। एक पृष्ठ हटाएँ या छोटे, स्पष्ट चित्र इस्तेमाल करें।", remove: "हटाएँ", page: "पृष्ठ", reference: "संदर्भ", report: "रिपोर्ट", normal: "सामान्य", low: "कम", high: "अधिक", borderline: "सीमांत", critical: "गंभीर"
  },
  bn: {
    eyebrow: "ব্যক্তিগত · সাইন-আপ নেই", heroTitle: "আপনার মেডিক্যাল রিপোর্ট,", heroEmphasis: "এবার সহজ ভাষায়।", heroBody: "ল্যাব রিপোর্ট বা প্রেসক্রিপশন আপলোড করুন। Lumen প্রতিটি মান বোঝায় এবং ডাক্তারকে জিজ্ঞাসার প্রশ্ন তৈরি করে।", neverStored: "কখনও সংরক্ষিত নয়", languages: "ভাষা", notDiagnosis: "রোগনির্ণয় নয় — সহজ ব্যাখ্যা", language: "ভাষা", explain: "আমার রিপোর্ট বুঝিয়ে দিন", drop: "রিপোর্ট এখানে দিন", uploadHint: "ল্যাব রিপোর্ট, প্রেসক্রিপশন বা ডিসচার্জ সারাংশ · JPG বা PNG · সর্বোচ্চ ৫ পৃষ্ঠা", findings: "আপনার ফলাফল", meaning: "এর অর্থ কী", questions: "ডাক্তারকে জিজ্ঞাসা করুন", lifestyle: "সাধারণ সুস্থতার পরামর্শ", copyQuestions: "প্রশ্ন কপি করুন", savePdf: "PDF সংরক্ষণ করুন", changeLanguage: "ভাষা বদলান", newReport: "নতুন রিপোর্ট", recentReports: "সাম্প্রতিক রিপোর্ট", clearHistory: "ইতিহাস মুছুন", noReports: "এখনও কোনো রিপোর্ট সংরক্ষিত নেই।", disclaimerTitle: "Lumen ডাক্তার নয়।", disclaimerBody: "এটি স্বাস্থ্যকর্মীর সঙ্গে ভালো আলোচনার জন্য মেডিক্যাল নথি বোঝায়। এটি রোগনির্ণয়, চিকিৎসা বা চিকিৎসা-পরামর্শের বিকল্প নয়। সব সময় যোগ্য চিকিৎসকের পরামর্শ নিন। ছবি বিশ্লেষণের জন্য নির্বাচিত AI প্রদানকারীর কাছে পাঠানো হয় এবং আমাদের সার্ভারে রাখা হয় না।", reading: "রিপোর্ট পড়া হচ্ছে…", translating: "অনুবাদ হচ্ছে…", copied: "✓ কপি হয়েছে", invalidFiles: "JPG বা PNG ছবি আপলোড করুন।", uploadFirst: "প্রথমে একটি রিপোর্ট আপলোড করুন।", tooManyPages: "সর্বোচ্চ ৫টি পৃষ্ঠা আপলোড করা যাবে।", payloadTooLarge: "পৃষ্ঠাগুলি খুব বড়। একটি পৃষ্ঠা সরান বা ছোট, পরিষ্কার ছবি ব্যবহার করুন।", remove: "সরান", page: "পৃষ্ঠা", reference: "রেফারেন্স", report: "রিপোর্ট", normal: "স্বাভাবিক", low: "কম", high: "বেশি", borderline: "সীমান্তবর্তী", critical: "গুরুতর"
  },
  as: {
    eyebrow: "ব্যক্তিগত · ছাইন-আপ নাই", heroTitle: "আপোনাৰ চিকিৎসা প্ৰতিবেদন,", heroEmphasis: "এতিয়া সহজ ভাষাত।", heroBody: "লেব প্ৰতিবেদন বা প্ৰেছক্ৰিপচন আপলোড কৰক। Lumen-এ প্ৰতিটো মান বুজাই আৰু চিকিৎসকক সুধিবলগীয়া প্ৰশ্ন সাজি দিয়ে।", neverStored: "কেতিয়াও সংৰক্ষণ নহয়", languages: "ভাষা", notDiagnosis: "ৰোগ নিৰ্ণয় নহয় — সহজ ব্যাখ্যা", language: "ভাষা", explain: "মোৰ প্ৰতিবেদন বুজাওক", drop: "প্ৰতিবেদন ইয়াত দিয়ক", uploadHint: "লেব প্ৰতিবেদন, প্ৰেছক্ৰিপচন বা ডিছচাৰ্জ সাৰাংশ · JPG বা PNG · সৰ্বাধিক ৫ পৃষ্ঠা", findings: "আপোনাৰ ফলাফল", meaning: "ইয়াৰ অৰ্থ কি", questions: "চিকিৎসকক সোধক", lifestyle: "সাধাৰণ সুস্থতাৰ পৰামৰ্শ", copyQuestions: "প্ৰশ্ন কপি কৰক", savePdf: "PDF সংৰক্ষণ কৰক", changeLanguage: "ভাষা সলনি কৰক", newReport: "নতুন প্ৰতিবেদন", recentReports: "শেহতীয়া প্ৰতিবেদন", clearHistory: "ইতিহাস মচক", noReports: "এতিয়ালৈ কোনো প্ৰতিবেদন সংৰক্ষণ কৰা নাই।", disclaimerTitle: "Lumen চিকিৎসক নহয়।", disclaimerBody: "ই চিকিৎসাকৰ্মীৰ সৈতে ভাল আলোচনাৰ বাবে চিকিৎসা নথি বুজাই দিয়ে। ই ৰোগ নিৰ্ণয়, চিকিৎসা বা চিকিৎসা পৰামৰ্শৰ বিকল্প নহয়। সদায় যোগ্য চিকিৎসকৰ পৰামৰ্শ লওক। ছবি বিশ্লেষণৰ বাবে নিৰ্বাচিত AI প্ৰদানকাৰীলৈ পঠোৱা হয় আৰু আমাৰ ছাৰ্ভাৰত সংৰক্ষণ কৰা নহয়।", reading: "প্ৰতিবেদন পঢ়ি থকা হৈছে…", translating: "অনুবাদ হৈ আছে…", copied: "✓ কপি হ’ল", invalidFiles: "JPG বা PNG ছবি আপলোড কৰক।", uploadFirst: "প্ৰথমে প্ৰতিবেদন আপলোড কৰক।", tooManyPages: "সৰ্বাধিক ৫টা পৃষ্ঠা আপলোড কৰিব পাৰিব।", payloadTooLarge: "পৃষ্ঠা অতি ডাঙৰ। এটা পৃষ্ঠা আঁতৰাওক বা সৰু, স্পষ্ট ছবি ব্যৱহাৰ কৰক।", remove: "আঁতৰাওক", page: "পৃষ্ঠা", reference: "প্ৰসংগ", report: "প্ৰতিবেদন", normal: "স্বাভাৱিক", low: "কম", high: "বেছি", borderline: "সীমান্তৱৰ্তী", critical: "গুৰুতৰ"
  },
  ta: {
    eyebrow: "தனிப்பட்டது · பதிவு தேவையில்லை", heroTitle: "உங்கள் மருத்துவ அறிக்கை,", heroEmphasis: "இப்போது எளிய சொற்களில்.", heroBody: "ஆய்வக அறிக்கை அல்லது மருந்துச் சீட்டை பதிவேற்றுங்கள். Lumen ஒவ்வொரு மதிப்பையும் விளக்கி மருத்துவரிடம் கேட்க வேண்டிய கேள்விகளைத் தயாரிக்கிறது.", neverStored: "ஒருபோதும் சேமிக்கப்படாது", languages: "மொழிகள்", notDiagnosis: "நோயறிதல் அல்ல — எளிய விளக்கம்", language: "மொழி", explain: "என் அறிக்கையை விளக்கவும்", drop: "அறிக்கையை இங்கே இடவும்", uploadHint: "ஆய்வக அறிக்கை, மருந்துச் சீட்டு அல்லது வெளியேற்றச் சுருக்கம் · JPG அல்லது PNG · 5 பக்கங்கள் வரை", findings: "உங்கள் முடிவுகள்", meaning: "இதன் பொருள்", questions: "மருத்துவரிடம் கேளுங்கள்", lifestyle: "பொதுவான நலக் குறிப்புகள்", copyQuestions: "கேள்விகளை நகலெடுக்கவும்", savePdf: "PDF ஆக சேமிக்கவும்", changeLanguage: "மொழியை மாற்றவும்", newReport: "புதிய அறிக்கை", recentReports: "சமீபத்திய அறிக்கைகள்", clearHistory: "வரலாற்றை அழிக்கவும்", noReports: "சேமித்த அறிக்கைகள் எதுவும் இல்லை.", disclaimerTitle: "Lumen ஒரு மருத்துவர் அல்ல.", disclaimerBody: "சுகாதார நிபுணர்களுடன் உரையாட உதவ மருத்துவ ஆவணங்களை இது விளக்குகிறது. இது நோயறிதல், சிகிச்சை அல்லது மருத்துவ ஆலோசனைக்கு மாற்றாகாது. தகுதியான மருத்துவரை எப்போதும் அணுகவும். படங்கள் தேர்ந்தெடுத்த AI வழங்குநருக்கு அனுப்பப்படுகின்றன; எங்கள் சேவையகங்களில் சேமிக்கப்படுவதில்லை.", reading: "அறிக்கை படிக்கப்படுகிறது…", translating: "மொழிபெயர்க்கப்படுகிறது…", copied: "✓ நகலெடுக்கப்பட்டது", invalidFiles: "JPG அல்லது PNG படங்களைப் பதிவேற்றவும்.", uploadFirst: "முதலில் அறிக்கையைப் பதிவேற்றவும்.", tooManyPages: "5 பக்கங்கள் வரை பதிவேற்றலாம்.", payloadTooLarge: "பக்கங்கள் மிகவும் பெரியவை. ஒரு பக்கத்தை நீக்கவும் அல்லது சிறிய தெளிவான படங்களைப் பயன்படுத்தவும்.", remove: "நீக்கு", page: "பக்கம்", reference: "குறிப்பு", report: "அறிக்கை", normal: "இயல்பு", low: "குறைவு", high: "அதிகம்", borderline: "எல்லைநிலை", critical: "மிகக் கடுமை"
  },
  te: {
    eyebrow: "వ్యక్తిగతం · సైన్-అప్ అవసరం లేదు", heroTitle: "మీ వైద్య నివేదిక,", heroEmphasis: "ఇప్పుడు సులభమైన మాటల్లో.", heroBody: "ల్యాబ్ రిపోర్ట్ లేదా ప్రిస్క్రిప్షన్‌ను అప్‌లోడ్ చేయండి. Lumen ప్రతి విలువను వివరిస్తూ వైద్యుడిని అడగాల్సిన ప్రశ్నలను సిద్ధం చేస్తుంది.", neverStored: "ఎప్పుడూ నిల్వ చేయము", languages: "భాషలు", notDiagnosis: "రోగ నిర్ధారణ కాదు — సరళ వివరణ", language: "భాష", explain: "నా నివేదికను వివరించండి", drop: "నివేదికను ఇక్కడ ఉంచండి", uploadHint: "ల్యాబ్ రిపోర్ట్, ప్రిస్క్రిప్షన్ లేదా డిశ్చార్జ్ సారాంశం · JPG లేదా PNG · 5 పేజీల వరకు", findings: "మీ ఫలితాలు", meaning: "దీని అర్థం", questions: "వైద్యుడిని అడగండి", lifestyle: "సాధారణ ఆరోగ్య సూచనలు", copyQuestions: "ప్రశ్నలను కాపీ చేయండి", savePdf: "PDFగా సేవ్ చేయండి", changeLanguage: "భాష మార్చండి", newReport: "కొత్త నివేదిక", recentReports: "ఇటీవలి నివేదికలు", clearHistory: "చరిత్రను తొలగించండి", noReports: "ఇంకా నివేదికలు సేవ్ కాలేదు.", disclaimerTitle: "Lumen వైద్యుడు కాదు.", disclaimerBody: "ఆరోగ్య నిపుణులతో మాట్లాడేందుకు వైద్య పత్రాలను ఇది వివరిస్తుంది. ఇది రోగ నిర్ధారణ, చికిత్స లేదా వైద్య సలహాకు ప్రత్యామ్నాయం కాదు. ఎల్లప్పుడూ అర్హతగల వైద్యుడిని సంప్రదించండి. చిత్రాలు విశ్లేషణ కోసం ఎంచుకున్న AI సేవకు పంపబడతాయి; మా సర్వర్లలో నిల్వ చేయబడవు.", reading: "నివేదిక చదువుతోంది…", translating: "అనువదిస్తోంది…", copied: "✓ కాపీ అయింది", invalidFiles: "JPG లేదా PNG చిత్రాలను అప్‌లోడ్ చేయండి.", uploadFirst: "ముందుగా నివేదికను అప్‌లోడ్ చేయండి.", tooManyPages: "5 పేజీల వరకు అప్‌లోడ్ చేయవచ్చు.", payloadTooLarge: "పేజీలు చాలా పెద్దవి. ఒక పేజీని తొలగించండి లేదా చిన్న స్పష్టమైన చిత్రాలను ఉపయోగించండి.", remove: "తొలగించు", page: "పేజీ", reference: "సూచన", report: "నివేదిక", normal: "సాధారణం", low: "తక్కువ", high: "ఎక్కువ", borderline: "సరిహద్దు", critical: "తీవ్రమైన"
  },
  mr: {
    eyebrow: "खासगी · साइन-अप नाही", heroTitle: "तुमचा वैद्यकीय अहवाल,", heroEmphasis: "आता सोप्या शब्दांत.", heroBody: "लॅब रिपोर्ट किंवा प्रिस्क्रिप्शन अपलोड करा. Lumen प्रत्येक मूल्य समजावते आणि डॉक्टरांना विचारायचे प्रश्न तयार करते.", neverStored: "कधीही साठवले जात नाही", languages: "भाषा", notDiagnosis: "निदान नाही — सोपे स्पष्टीकरण", language: "भाषा", explain: "माझा अहवाल समजावून सांगा", drop: "अहवाल येथे टाका", uploadHint: "लॅब रिपोर्ट, प्रिस्क्रिप्शन किंवा डिस्चार्ज सारांश · JPG किंवा PNG · जास्तीत जास्त ५ पाने", findings: "तुमचे निकाल", meaning: "याचा अर्थ", questions: "डॉक्टरांना विचारा", lifestyle: "सामान्य आरोग्य सूचना", copyQuestions: "प्रश्न कॉपी करा", savePdf: "PDF जतन करा", changeLanguage: "भाषा बदला", newReport: "नवीन अहवाल", recentReports: "अलीकडील अहवाल", clearHistory: "इतिहास मिटवा", noReports: "अजून कोणताही अहवाल जतन केलेला नाही.", disclaimerTitle: "Lumen डॉक्टर नाही.", disclaimerBody: "आरोग्य व्यावसायिकांशी संवाद साधण्यासाठी हे वैद्यकीय कागदपत्रे समजावते. हे निदान, उपचार किंवा वैद्यकीय सल्ल्याचा पर्याय नाही. नेहमी पात्र डॉक्टरांचा सल्ला घ्या. चित्रे विश्लेषणासाठी निवडलेल्या AI प्रदात्याकडे पाठवली जातात आणि आमच्या सर्व्हरवर साठवली जात नाहीत.", reading: "अहवाल वाचला जात आहे…", translating: "भाषांतर होत आहे…", copied: "✓ कॉपी झाले", invalidFiles: "JPG किंवा PNG चित्रे अपलोड करा.", uploadFirst: "प्रथम अहवाल अपलोड करा.", tooManyPages: "जास्तीत जास्त ५ पाने अपलोड करू शकता.", payloadTooLarge: "पाने खूप मोठी आहेत. एक पान काढा किंवा लहान, स्पष्ट चित्रे वापरा.", remove: "काढा", page: "पान", reference: "संदर्भ", report: "अहवाल", normal: "सामान्य", low: "कमी", high: "जास्त", borderline: "सीमारेषेवर", critical: "गंभीर"
  },
  kn: {
    eyebrow: "ಖಾಸಗಿ · ಸೈನ್-ಅಪ್ ಬೇಡ", heroTitle: "ನಿಮ್ಮ ವೈದ್ಯಕೀಯ ವರದಿ,", heroEmphasis: "ಈಗ ಸರಳ ಪದಗಳಲ್ಲಿ.", heroBody: "ಲ್ಯಾಬ್ ವರದಿ ಅಥವಾ ಔಷಧ ಚೀಟಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ. Lumen ಪ್ರತಿಯೊಂದು ಮೌಲ್ಯವನ್ನು ವಿವರಿಸಿ ವೈದ್ಯರನ್ನು ಕೇಳಬೇಕಾದ ಪ್ರಶ್ನೆಗಳನ್ನು ಸಿದ್ಧಪಡಿಸುತ್ತದೆ.", neverStored: "ಎಂದಿಗೂ ಸಂಗ್ರಹಿಸುವುದಿಲ್ಲ", languages: "ಭಾಷೆಗಳು", notDiagnosis: "ರೋಗನಿರ್ಣಯವಲ್ಲ — ಸರಳ ವಿವರಣೆ", language: "ಭಾಷೆ", explain: "ನನ್ನ ವರದಿಯನ್ನು ವಿವರಿಸಿ", drop: "ವರದಿಯನ್ನು ಇಲ್ಲಿ ಹಾಕಿ", uploadHint: "ಲ್ಯಾಬ್ ವರದಿ, ಔಷಧ ಚೀಟಿ ಅಥವಾ ಡಿಸ್ಚಾರ್ಜ್ ಸಾರಾಂಶ · JPG ಅಥವಾ PNG · 5 ಪುಟಗಳವರೆಗೆ", findings: "ನಿಮ್ಮ ಫಲಿತಾಂಶಗಳು", meaning: "ಇದರ ಅರ್ಥ", questions: "ವೈದ್ಯರನ್ನು ಕೇಳಿ", lifestyle: "ಸಾಮಾನ್ಯ ಆರೋಗ್ಯ ಸೂಚನೆಗಳು", copyQuestions: "ಪ್ರಶ್ನೆಗಳನ್ನು ನಕಲಿಸಿ", savePdf: "PDF ಆಗಿ ಉಳಿಸಿ", changeLanguage: "ಭಾಷೆ ಬದಲಿಸಿ", newReport: "ಹೊಸ ವರದಿ", recentReports: "ಇತ್ತೀಚಿನ ವರದಿಗಳು", clearHistory: "ಇತಿಹಾಸ ಅಳಿಸಿ", noReports: "ಇನ್ನೂ ವರದಿಗಳು ಉಳಿಸಿಲ್ಲ.", disclaimerTitle: "Lumen ವೈದ್ಯರಲ್ಲ.", disclaimerBody: "ಆರೋಗ್ಯ ವೃತ್ತಿಪರರೊಂದಿಗೆ ಮಾತನಾಡಲು ವೈದ್ಯಕೀಯ ದಾಖಲೆಗಳನ್ನು ಇದು ವಿವರಿಸುತ್ತದೆ. ಇದು ರೋಗನಿರ್ಣಯ, ಚಿಕಿತ್ಸೆ ಅಥವಾ ವೈದ್ಯಕೀಯ ಸಲಹೆಗೆ ಪರ್ಯಾಯವಲ್ಲ. ಯಾವಾಗಲೂ ಅರ್ಹ ವೈದ್ಯರನ್ನು ಸಂಪರ್ಕಿಸಿ. ಚಿತ್ರಗಳನ್ನು ವಿಶ್ಲೇಷಣೆಗೆ ಆಯ್ದ AI ಪೂರೈಕೆದಾರರಿಗೆ ಕಳುಹಿಸಲಾಗುತ್ತದೆ; ನಮ್ಮ ಸರ್ವರ್‌ಗಳಲ್ಲಿ ಸಂಗ್ರಹಿಸಲಾಗುವುದಿಲ್ಲ.", reading: "ವರದಿ ಓದಲಾಗುತ್ತಿದೆ…", translating: "ಅನುವಾದಿಸಲಾಗುತ್ತಿದೆ…", copied: "✓ ನಕಲಿಸಲಾಗಿದೆ", invalidFiles: "JPG ಅಥವಾ PNG ಚಿತ್ರಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.", uploadFirst: "ಮೊದಲು ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.", tooManyPages: "5 ಪುಟಗಳವರೆಗೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಬಹುದು.", payloadTooLarge: "ಪುಟಗಳು ತುಂಬಾ ದೊಡ್ಡದಾಗಿವೆ. ಒಂದು ಪುಟ ತೆಗೆದುಹಾಕಿ ಅಥವಾ ಸಣ್ಣ ಸ್ಪಷ್ಟ ಚಿತ್ರಗಳನ್ನು ಬಳಸಿ.", remove: "ತೆಗೆದುಹಾಕಿ", page: "ಪುಟ", reference: "ಉಲ್ಲೇಖ", report: "ವರದಿ", normal: "ಸಾಮಾನ್ಯ", low: "ಕಡಿಮೆ", high: "ಹೆಚ್ಚು", borderline: "ಗಡಿಭಾಗ", critical: "ಗಂಭೀರ"
  },
  gu: {
    eyebrow: "ખાનગી · સાઇન-અપ નહીં", heroTitle: "તમારો તબીબી અહેવાલ,", heroEmphasis: "હવે સરળ શબ્દોમાં.", heroBody: "લેબ રિપોર્ટ અથવા પ્રિસ્ક્રિપ્શન અપલોડ કરો. Lumen દરેક મૂલ્ય સમજાવે છે અને ડૉક્ટરને પૂછવાના પ્રશ્નો તૈયાર કરે છે.", neverStored: "ક્યારેય સંગ્રહિત નહીં", languages: "ભાષાઓ", notDiagnosis: "નિદાન નહીં — સરળ સમજ", language: "ભાષા", explain: "મારો અહેવાલ સમજાવો", drop: "અહેવાલ અહીં મૂકો", uploadHint: "લેબ રિપોર્ટ, પ્રિસ્ક્રિપ્શન અથવા ડિસ્ચાર્જ સારાંશ · JPG અથવા PNG · વધુમાં વધુ ૫ પાનાં", findings: "તમારા પરિણામો", meaning: "આનો અર્થ", questions: "ડૉક્ટરને પૂછો", lifestyle: "સામાન્ય સુખાકારી સૂચનો", copyQuestions: "પ્રશ્નો કૉપિ કરો", savePdf: "PDF સાચવો", changeLanguage: "ભાષા બદલો", newReport: "નવો અહેવાલ", recentReports: "તાજેતરના અહેવાલો", clearHistory: "ઇતિહાસ સાફ કરો", noReports: "હજુ કોઈ અહેવાલ સાચવ્યો નથી.", disclaimerTitle: "Lumen ડૉક્ટર નથી.", disclaimerBody: "આરોગ્ય નિષ્ણાતો સાથે વાત કરવામાં મદદ માટે તે તબીબી દસ્તાવેજો સમજાવે છે. તે નિદાન, સારવાર અથવા તબીબી સલાહનો વિકલ્પ નથી. હંમેશાં લાયક ડૉક્ટરની સલાહ લો. ચિત્રો વિશ્લેષણ માટે પસંદ કરેલા AI પ્રદાતાને મોકલાય છે અને અમારા સર્વર પર સંગ્રહિત થતા નથી.", reading: "અહેવાલ વાંચી રહ્યા છીએ…", translating: "અનુવાદ થઈ રહ્યો છે…", copied: "✓ કૉપિ થયું", invalidFiles: "JPG અથવા PNG ચિત્રો અપલોડ કરો.", uploadFirst: "પહેલા અહેવાલ અપલોડ કરો.", tooManyPages: "વધુમાં વધુ ૫ પાનાં અપલોડ કરી શકો છો.", payloadTooLarge: "પાનાં બહુ મોટાં છે. એક પાનું દૂર કરો અથવા નાનાં સ્પષ્ટ ચિત્રો વાપરો.", remove: "દૂર કરો", page: "પાનું", reference: "સંદર્ભ", report: "અહેવાલ", normal: "સામાન્ય", low: "ઓછું", high: "વધુ", borderline: "સીમાવર્તી", critical: "ગંભીર"
  },
  ml: {
    eyebrow: "സ്വകാര്യം · സൈൻ-അപ്പ് വേണ്ട", heroTitle: "നിങ്ങളുടെ മെഡിക്കൽ റിപ്പോർട്ട്,", heroEmphasis: "ഇപ്പോൾ ലളിതമായ വാക്കുകളിൽ.", heroBody: "ലാബ് റിപ്പോർട്ടോ മരുന്നുകുറിപ്പോ അപ്‌ലോഡ് ചെയ്യുക. Lumen ഓരോ മൂല്യവും വിശദീകരിച്ച് ഡോക്ടറോട് ചോദിക്കാനുള്ള ചോദ്യങ്ങൾ തയ്യാറാക്കുന്നു.", neverStored: "ഒരിക്കലും സംഭരിക്കില്ല", languages: "ഭാഷകൾ", notDiagnosis: "രോഗനിർണയം അല്ല — ലളിതമായ വിശദീകരണം", language: "ഭാഷ", explain: "എന്റെ റിപ്പോർട്ട് വിശദീകരിക്കുക", drop: "റിപ്പോർട്ട് ഇവിടെ ഇടുക", uploadHint: "ലാബ് റിപ്പോർട്ട്, മരുന്നുകുറിപ്പ് അല്ലെങ്കിൽ ഡിസ്ചാർജ് സംഗ്രഹം · JPG അല്ലെങ്കിൽ PNG · 5 പേജ് വരെ", findings: "നിങ്ങളുടെ ഫലങ്ങൾ", meaning: "ഇതിന്റെ അർത്ഥം", questions: "ഡോക്ടറോട് ചോദിക്കുക", lifestyle: "പൊതുവായ ആരോഗ്യ നിർദേശങ്ങൾ", copyQuestions: "ചോദ്യങ്ങൾ പകർത്തുക", savePdf: "PDF ആയി സൂക്ഷിക്കുക", changeLanguage: "ഭാഷ മാറ്റുക", newReport: "പുതിയ റിപ്പോർട്ട്", recentReports: "സമീപകാല റിപ്പോർട്ടുകൾ", clearHistory: "ചരിത്രം മായ്ക്കുക", noReports: "ഇതുവരെ റിപ്പോർട്ടുകളൊന്നും സൂക്ഷിച്ചിട്ടില്ല.", disclaimerTitle: "Lumen ഒരു ഡോക്ടറല്ല.", disclaimerBody: "ആരോഗ്യ വിദഗ്ധരുമായി സംസാരിക്കാൻ സഹായിക്കുന്നതിനായി ഇത് മെഡിക്കൽ രേഖകൾ വിശദീകരിക്കുന്നു. ഇത് രോഗനിർണയം, ചികിത്സ, അല്ലെങ്കിൽ മെഡിക്കൽ ഉപദേശം എന്നിവയ്ക്ക് പകരമല്ല. യോഗ്യനായ ഡോക്ടറെ എപ്പോഴും സമീപിക്കുക. ചിത്രങ്ങൾ വിശകലനത്തിനായി തിരഞ്ഞെടുത്ത AI ദാതാവിന് അയയ്ക്കുന്നു; ഞങ്ങളുടെ സെർവറുകളിൽ സംഭരിക്കുന്നില്ല.", reading: "റിപ്പോർട്ട് വായിക്കുന്നു…", translating: "വിവർത്തനം ചെയ്യുന്നു…", copied: "✓ പകർത്തി", invalidFiles: "JPG അല്ലെങ്കിൽ PNG ചിത്രങ്ങൾ അപ്‌ലോഡ് ചെയ്യുക.", uploadFirst: "ആദ്യം റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക.", tooManyPages: "5 പേജ് വരെ അപ്‌ലോഡ് ചെയ്യാം.", payloadTooLarge: "പേജുകൾ വളരെ വലുതാണ്. ഒരു പേജ് നീക്കുക അല്ലെങ്കിൽ ചെറിയ വ്യക്തമായ ചിത്രങ്ങൾ ഉപയോഗിക്കുക.", remove: "നീക്കുക", page: "പേജ്", reference: "സൂചന", report: "റിപ്പോർട്ട്", normal: "സാധാരണം", low: "കുറവ്", high: "കൂടുതൽ", borderline: "അതിർത്തി", critical: "ഗുരുതരം"
  },
  pa: {
    eyebrow: "ਨਿੱਜੀ · ਸਾਈਨ-ਅੱਪ ਨਹੀਂ", heroTitle: "ਤੁਹਾਡੀ ਮੈਡੀਕਲ ਰਿਪੋਰਟ,", heroEmphasis: "ਹੁਣ ਸੌਖੇ ਸ਼ਬਦਾਂ ਵਿੱਚ।", heroBody: "ਲੈਬ ਰਿਪੋਰਟ ਜਾਂ ਨੁਸਖ਼ਾ ਅੱਪਲੋਡ ਕਰੋ। Lumen ਹਰ ਮੁੱਲ ਸਮਝਾਉਂਦਾ ਹੈ ਅਤੇ ਡਾਕਟਰ ਨੂੰ ਪੁੱਛਣ ਲਈ ਸਵਾਲ ਤਿਆਰ ਕਰਦਾ ਹੈ।", neverStored: "ਕਦੇ ਸੰਭਾਲਿਆ ਨਹੀਂ ਜਾਂਦਾ", languages: "ਭਾਸ਼ਾਵਾਂ", notDiagnosis: "ਤਸ਼ਖ਼ੀਸ ਨਹੀਂ — ਸੌਖੀ ਵਿਆਖਿਆ", language: "ਭਾਸ਼ਾ", explain: "ਮੇਰੀ ਰਿਪੋਰਟ ਸਮਝਾਓ", drop: "ਰਿਪੋਰਟ ਇੱਥੇ ਪਾਓ", uploadHint: "ਲੈਬ ਰਿਪੋਰਟ, ਨੁਸਖ਼ਾ ਜਾਂ ਡਿਸਚਾਰਜ ਸਾਰ · JPG ਜਾਂ PNG · ਵੱਧ ਤੋਂ ਵੱਧ ੫ ਸਫ਼ੇ", findings: "ਤੁਹਾਡੇ ਨਤੀਜੇ", meaning: "ਇਸਦਾ ਅਰਥ", questions: "ਡਾਕਟਰ ਨੂੰ ਪੁੱਛੋ", lifestyle: "ਆਮ ਤੰਦਰੁਸਤੀ ਸੁਝਾਅ", copyQuestions: "ਸਵਾਲ ਕਾਪੀ ਕਰੋ", savePdf: "PDF ਸੰਭਾਲੋ", changeLanguage: "ਭਾਸ਼ਾ ਬਦਲੋ", newReport: "ਨਵੀਂ ਰਿਪੋਰਟ", recentReports: "ਹਾਲੀਆ ਰਿਪੋਰਟਾਂ", clearHistory: "ਇਤਿਹਾਸ ਮਿਟਾਓ", noReports: "ਹਾਲੇ ਕੋਈ ਰਿਪੋਰਟ ਸੰਭਾਲੀ ਨਹੀਂ।", disclaimerTitle: "Lumen ਡਾਕਟਰ ਨਹੀਂ ਹੈ।", disclaimerBody: "ਇਹ ਸਿਹਤ ਮਾਹਿਰਾਂ ਨਾਲ ਗੱਲ ਕਰਨ ਲਈ ਮੈਡੀਕਲ ਦਸਤਾਵੇਜ਼ ਸਮਝਾਉਂਦਾ ਹੈ। ਇਹ ਤਸ਼ਖ਼ੀਸ, ਇਲਾਜ ਜਾਂ ਮੈਡੀਕਲ ਸਲਾਹ ਦਾ ਬਦਲ ਨਹੀਂ ਹੈ। ਹਮੇਸ਼ਾਂ ਯੋਗ ਡਾਕਟਰ ਨਾਲ ਸਲਾਹ ਕਰੋ। ਤਸਵੀਰਾਂ ਵਿਸ਼ਲੇਸ਼ਣ ਲਈ ਚੁਣੇ AI ਪ੍ਰਦਾਤਾ ਨੂੰ ਭੇਜੀਆਂ ਜਾਂਦੀਆਂ ਹਨ ਅਤੇ ਸਾਡੇ ਸਰਵਰਾਂ ਉੱਤੇ ਸੰਭਾਲੀਆਂ ਨਹੀਂ ਜਾਂਦੀਆਂ।", reading: "ਰਿਪੋਰਟ ਪੜ੍ਹੀ ਜਾ ਰਹੀ ਹੈ…", translating: "ਅਨੁਵਾਦ ਹੋ ਰਿਹਾ ਹੈ…", copied: "✓ ਕਾਪੀ ਹੋਇਆ", invalidFiles: "JPG ਜਾਂ PNG ਤਸਵੀਰਾਂ ਅੱਪਲੋਡ ਕਰੋ।", uploadFirst: "ਪਹਿਲਾਂ ਰਿਪੋਰਟ ਅੱਪਲੋਡ ਕਰੋ।", tooManyPages: "ਵੱਧ ਤੋਂ ਵੱਧ ੫ ਸਫ਼ੇ ਅੱਪਲੋਡ ਕਰ ਸਕਦੇ ਹੋ।", payloadTooLarge: "ਸਫ਼ੇ ਬਹੁਤ ਵੱਡੇ ਹਨ। ਇੱਕ ਸਫ਼ਾ ਹਟਾਓ ਜਾਂ ਛੋਟੀਆਂ ਸਾਫ਼ ਤਸਵੀਰਾਂ ਵਰਤੋ।", remove: "ਹਟਾਓ", page: "ਸਫ਼ਾ", reference: "ਹਵਾਲਾ", report: "ਰਿਪੋਰਟ", normal: "ਸਧਾਰਨ", low: "ਘੱਟ", high: "ਵੱਧ", borderline: "ਸੀਮਾਵਰਤੀ", critical: "ਗੰਭੀਰ"
  },
  or: {
    eyebrow: "ବ୍ୟକ୍ତିଗତ · ସାଇନ୍-ଅପ୍ ନାହିଁ", heroTitle: "ଆପଣଙ୍କ ଚିକିତ୍ସା ରିପୋର୍ଟ,", heroEmphasis: "ଏବେ ସରଳ ଶବ୍ଦରେ।", heroBody: "ଲ୍ୟାବ୍ ରିପୋର୍ଟ କିମ୍ବା ପ୍ରେସକ୍ରିପସନ୍ ଅପଲୋଡ୍ କରନ୍ତୁ। Lumen ପ୍ରତ୍ୟେକ ମୂଲ୍ୟ ବୁଝାଏ ଏବଂ ଡାକ୍ତରଙ୍କୁ ପଚାରିବା ପ୍ରଶ୍ନ ପ୍ରସ୍ତୁତ କରେ।", neverStored: "କେବେ ସଞ୍ଚିତ ହୁଏ ନାହିଁ", languages: "ଭାଷା", notDiagnosis: "ରୋଗ ନିର୍ଣ୍ଣୟ ନୁହେଁ — ସରଳ ବ୍ୟାଖ୍ୟା", language: "ଭାଷା", explain: "ମୋ ରିପୋର୍ଟ ବୁଝାନ୍ତୁ", drop: "ରିପୋର୍ଟ ଏଠାରେ ଦିଅନ୍ତୁ", uploadHint: "ଲ୍ୟାବ୍ ରିପୋର୍ଟ, ପ୍ରେସକ୍ରିପସନ୍ କିମ୍ବା ଡିସଚାର୍ଜ ସାରାଂଶ · JPG କିମ୍ବା PNG · ସର୍ବାଧିକ ୫ ପୃଷ୍ଠା", findings: "ଆପଣଙ୍କ ଫଳାଫଳ", meaning: "ଏହାର ଅର୍ଥ", questions: "ଡାକ୍ତରଙ୍କୁ ପଚାରନ୍ତୁ", lifestyle: "ସାଧାରଣ ସୁସ୍ଥତା ପରାମର୍ଶ", copyQuestions: "ପ୍ରଶ୍ନ କପି କରନ୍ତୁ", savePdf: "PDF ସଞ୍ଚୟ କରନ୍ତୁ", changeLanguage: "ଭାଷା ବଦଳାନ୍ତୁ", newReport: "ନୂଆ ରିପୋର୍ଟ", recentReports: "ସାମ୍ପ୍ରତିକ ରିପୋର୍ଟ", clearHistory: "ଇତିହାସ ସଫା କରନ୍ତୁ", noReports: "ଏପର୍ଯ୍ୟନ୍ତ କୌଣସି ରିପୋର୍ଟ ସଞ୍ଚିତ ନାହିଁ।", disclaimerTitle: "Lumen ଡାକ୍ତର ନୁହେଁ।", disclaimerBody: "ସ୍ୱାସ୍ଥ୍ୟ ବିଶେଷଜ୍ଞଙ୍କ ସହ କଥା ହେବାରେ ସାହାଯ୍ୟ ପାଇଁ ଏହା ଚିକିତ୍ସା ଦଲିଲ ବୁଝାଏ। ଏହା ରୋଗ ନିର୍ଣ୍ଣୟ, ଚିକିତ୍ସା କିମ୍ବା ଚିକିତ୍ସା ପରାମର୍ଶର ବିକଳ୍ପ ନୁହେଁ। ସବୁବେଳେ ଯୋଗ୍ୟ ଡାକ୍ତରଙ୍କ ପରାମର୍ଶ ନିଅନ୍ତୁ। ଛବି ବିଶ୍ଳେଷଣ ପାଇଁ ଚୟନିତ AI ପ୍ରଦାନକାରୀଙ୍କୁ ପଠାଯାଏ ଏବଂ ଆମ ସର୍ଭରରେ ସଞ୍ଚିତ ହୁଏ ନାହିଁ।", reading: "ରିପୋର୍ଟ ପଢ଼ାଯାଉଛି…", translating: "ଅନୁବାଦ ହେଉଛି…", copied: "✓ କପି ହେଲା", invalidFiles: "JPG କିମ୍ବା PNG ଛବି ଅପଲୋଡ୍ କରନ୍ତୁ।", uploadFirst: "ପ୍ରଥମେ ରିପୋର୍ଟ ଅପଲୋଡ୍ କରନ୍ତୁ।", tooManyPages: "ସର୍ବାଧିକ ୫ ପୃଷ୍ଠା ଅପଲୋଡ୍ କରିପାରିବେ।", payloadTooLarge: "ପୃଷ୍ଠାଗୁଡ଼ିକ ବହୁତ ବଡ଼। ଗୋଟିଏ ପୃଷ୍ଠା କାଢ଼ନ୍ତୁ କିମ୍ବା ଛୋଟ ସ୍ପଷ୍ଟ ଛବି ବ୍ୟବହାର କରନ୍ତୁ।", remove: "କାଢ଼ନ୍ତୁ", page: "ପୃଷ୍ଠା", reference: "ସନ୍ଦର୍ଭ", report: "ରିପୋର୍ଟ", normal: "ସାଧାରଣ", low: "କମ୍", high: "ଅଧିକ", borderline: "ସୀମାନ୍ତ", critical: "ଗୁରୁତର"
  },
  ur: {
    eyebrow: "نجی · سائن اپ نہیں", heroTitle: "آپ کی طبی رپورٹ،", heroEmphasis: "اب آسان الفاظ میں۔", heroBody: "لیب رپورٹ یا نسخہ اپ لوڈ کریں۔ Lumen ہر قدر سمجھاتا ہے اور ڈاکٹر سے پوچھنے کے سوالات تیار کرتا ہے۔", neverStored: "کبھی محفوظ نہیں کیا جاتا", languages: "زبانیں", notDiagnosis: "تشخیص نہیں — آسان وضاحت", language: "زبان", explain: "میری رپورٹ سمجھائیں", drop: "رپورٹ یہاں ڈالیں", uploadHint: "لیب رپورٹ، نسخہ یا ڈسچارج خلاصہ · JPG یا PNG · زیادہ سے زیادہ ۵ صفحات", findings: "آپ کے نتائج", meaning: "اس کا مطلب", questions: "ڈاکٹر سے پوچھیں", lifestyle: "عمومی صحت کی تجاویز", copyQuestions: "سوالات کاپی کریں", savePdf: "PDF محفوظ کریں", changeLanguage: "زبان بدلیں", newReport: "نئی رپورٹ", recentReports: "حالیہ رپورٹس", clearHistory: "تاریخ صاف کریں", noReports: "ابھی کوئی رپورٹ محفوظ نہیں۔", disclaimerTitle: "Lumen ڈاکٹر نہیں ہے۔", disclaimerBody: "یہ صحت کے ماہرین سے بہتر گفتگو کے لیے طبی دستاویزات سمجھاتا ہے۔ یہ تشخیص، علاج یا طبی مشورے کا متبادل نہیں۔ ہمیشہ مستند ڈاکٹر سے مشورہ کریں۔ تصاویر تجزیے کے لیے منتخب AI فراہم کنندہ کو بھیجی جاتی ہیں اور ہمارے سرور پر محفوظ نہیں ہوتیں۔", reading: "رپورٹ پڑھی جا رہی ہے…", translating: "ترجمہ ہو رہا ہے…", copied: "✓ کاپی ہوگیا", invalidFiles: "براہ کرم JPG یا PNG تصاویر اپ لوڈ کریں۔", uploadFirst: "پہلے رپورٹ اپ لوڈ کریں۔", tooManyPages: "زیادہ سے زیادہ ۵ صفحات اپ لوڈ کیے جا سکتے ہیں۔", payloadTooLarge: "صفحات بہت بڑے ہیں۔ ایک صفحہ ہٹائیں یا چھوٹی، واضح تصاویر استعمال کریں۔", remove: "ہٹائیں", page: "صفحہ", reference: "حوالہ", report: "رپورٹ", normal: "معمول", low: "کم", high: "زیادہ", borderline: "حد کے قریب", critical: "انتہائی سنگین"
  }
};

const reviewTranslations = {
  en: { reviewTitle: "Check uncertain values", reviewIntro: "The highlighted text was difficult to read. Compare it with the report and correct anything that is wrong before Lumen explains it.", confidence: "Confidence", highConfidence: "Clear", mediumConfidence: "Check", lowConfidence: "Unclear", confirmValues: "Confirm and explain", cancelReview: "Cancel", uncertainValues: "values need checking", fieldTest: "Test", fieldValue: "Value", fieldUnit: "Unit" },
  hi: { reviewTitle: "अस्पष्ट मान जाँचें", reviewIntro: "चिह्नित पाठ पढ़ना कठिन था। रिपोर्ट से मिलाएँ और व्याख्या से पहले गलत जानकारी सुधारें।", confidence: "विश्वास", highConfidence: "स्पष्ट", mediumConfidence: "जाँचें", lowConfidence: "अस्पष्ट", confirmValues: "पुष्टि करें और समझाएँ", cancelReview: "रद्द करें", uncertainValues: "मान जाँचने हैं", fieldTest: "जाँच", fieldValue: "मान", fieldUnit: "इकाई" },
  bn: { reviewTitle: "অনিশ্চিত মান যাচাই করুন", reviewIntro: "চিহ্নিত লেখা পড়া কঠিন ছিল। রিপোর্টের সঙ্গে মিলিয়ে ভুল তথ্য ঠিক করুন।", confidence: "নিশ্চয়তা", highConfidence: "স্পষ্ট", mediumConfidence: "যাচাই করুন", lowConfidence: "অস্পষ্ট", confirmValues: "নিশ্চিত করে ব্যাখ্যা করুন", cancelReview: "বাতিল", uncertainValues: "টি মান যাচাই দরকার", fieldTest: "পরীক্ষা", fieldValue: "মান", fieldUnit: "একক" },
  as: { reviewTitle: "অনিশ্চিত মান পৰীক্ষা কৰক", reviewIntro: "চিহ্নিত লিখনি পঢ়িবলৈ কঠিন আছিল। প্ৰতিবেদনৰ সৈতে মিলাই ভুল তথ্য শুধৰাওক।", confidence: "নিশ্চয়তা", highConfidence: "স্পষ্ট", mediumConfidence: "পৰীক্ষা কৰক", lowConfidence: "অস্পষ্ট", confirmValues: "নিশ্চিত কৰি বুজাওক", cancelReview: "বাতিল", uncertainValues: "টা মান পৰীক্ষা কৰিব লাগিব", fieldTest: "পৰীক্ষা", fieldValue: "মান", fieldUnit: "একক" },
  ta: { reviewTitle: "தெளிவற்ற மதிப்புகளைச் சரிபார்க்கவும்", reviewIntro: "குறிக்கப்பட்ட எழுத்து படிக்க கடினமாக இருந்தது. அறிக்கையுடன் ஒப்பிட்டு தவறுகளைத் திருத்தவும்.", confidence: "நம்பகத்தன்மை", highConfidence: "தெளிவு", mediumConfidence: "சரிபார்க்கவும்", lowConfidence: "தெளிவில்லை", confirmValues: "உறுதிசெய்து விளக்கவும்", cancelReview: "ரத்துசெய்", uncertainValues: "மதிப்புகளைச் சரிபார்க்க வேண்டும்", fieldTest: "பரிசோதனை", fieldValue: "மதிப்பு", fieldUnit: "அலகு" },
  te: { reviewTitle: "అస్పష్టమైన విలువలను తనిఖీ చేయండి", reviewIntro: "గుర్తించిన వచనం చదవడం కష్టంగా ఉంది. నివేదికతో పోల్చి తప్పులను సరిచేయండి.", confidence: "నమ్మకం", highConfidence: "స్పష్టం", mediumConfidence: "తనిఖీ", lowConfidence: "అస్పష్టం", confirmValues: "నిర్ధారించి వివరించండి", cancelReview: "రద్దు", uncertainValues: "విలువలను తనిఖీ చేయాలి", fieldTest: "పరీక్ష", fieldValue: "విలువ", fieldUnit: "యూనిట్" },
  mr: { reviewTitle: "अस्पष्ट मूल्ये तपासा", reviewIntro: "चिन्हांकित मजकूर वाचणे कठीण होते. अहवालाशी तुलना करून चुका दुरुस्त करा.", confidence: "विश्वास", highConfidence: "स्पष्ट", mediumConfidence: "तपासा", lowConfidence: "अस्पष्ट", confirmValues: "पुष्टी करून समजवा", cancelReview: "रद्द करा", uncertainValues: "मूल्ये तपासायची आहेत", fieldTest: "चाचणी", fieldValue: "मूल्य", fieldUnit: "एकक" },
  kn: { reviewTitle: "ಅಸ್ಪಷ್ಟ ಮೌಲ್ಯಗಳನ್ನು ಪರಿಶೀಲಿಸಿ", reviewIntro: "ಗುರುತಿಸಿದ ಪಠ್ಯವನ್ನು ಓದುವುದು ಕಷ್ಟವಾಗಿತ್ತು. ವರದಿಯೊಂದಿಗೆ ಹೋಲಿಸಿ ತಪ್ಪುಗಳನ್ನು ಸರಿಪಡಿಸಿ.", confidence: "ವಿಶ್ವಾಸ", highConfidence: "ಸ್ಪಷ್ಟ", mediumConfidence: "ಪರಿಶೀಲಿಸಿ", lowConfidence: "ಅಸ್ಪಷ್ಟ", confirmValues: "ದೃಢೀಕರಿಸಿ ವಿವರಿಸಿ", cancelReview: "ರದ್ದು", uncertainValues: "ಮೌಲ್ಯಗಳನ್ನು ಪರಿಶೀಲಿಸಬೇಕು", fieldTest: "ಪರೀಕ್ಷೆ", fieldValue: "ಮೌಲ್ಯ", fieldUnit: "ಘಟಕ" },
  gu: { reviewTitle: "અસ્પષ્ટ મૂલ્યો તપાસો", reviewIntro: "ચિહ્નિત લખાણ વાંચવું મુશ્કેલ હતું. અહેવાલ સાથે સરખાવી ભૂલો સુધારો.", confidence: "વિશ્વાસ", highConfidence: "સ્પષ્ટ", mediumConfidence: "તપાસો", lowConfidence: "અસ્પષ્ટ", confirmValues: "ખાતરી કરીને સમજાવો", cancelReview: "રદ કરો", uncertainValues: "મૂલ્યો તપાસવાના છે", fieldTest: "તપાસ", fieldValue: "મૂલ્ય", fieldUnit: "એકમ" },
  ml: { reviewTitle: "അവ്യക്തമായ മൂല്യങ്ങൾ പരിശോധിക്കുക", reviewIntro: "അടയാളപ്പെടുത്തിയ എഴുത്ത് വായിക്കാൻ ബുദ്ധിമുട്ടായിരുന്നു. റിപ്പോർട്ടുമായി താരതമ്യം ചെയ്ത് തെറ്റുകൾ തിരുത്തുക.", confidence: "വിശ്വാസം", highConfidence: "വ്യക്തം", mediumConfidence: "പരിശോധിക്കുക", lowConfidence: "അവ്യക്തം", confirmValues: "സ്ഥിരീകരിച്ച് വിശദീകരിക്കുക", cancelReview: "റദ്ദാക്കുക", uncertainValues: "മൂല്യങ്ങൾ പരിശോധിക്കണം", fieldTest: "പരിശോധന", fieldValue: "മൂല്യം", fieldUnit: "യൂണിറ്റ്" },
  pa: { reviewTitle: "ਅਸਪਸ਼ਟ ਮੁੱਲ ਜਾਂਚੋ", reviewIntro: "ਨਿਸ਼ਾਨ ਲਗਾਇਆ ਲਿਖਤ ਪੜ੍ਹਨਾ ਔਖਾ ਸੀ। ਰਿਪੋਰਟ ਨਾਲ ਮਿਲਾ ਕੇ ਗਲਤੀਆਂ ਠੀਕ ਕਰੋ।", confidence: "ਭਰੋਸਾ", highConfidence: "ਸਪਸ਼ਟ", mediumConfidence: "ਜਾਂਚੋ", lowConfidence: "ਅਸਪਸ਼ਟ", confirmValues: "ਪੁਸ਼ਟੀ ਕਰਕੇ ਸਮਝਾਓ", cancelReview: "ਰੱਦ ਕਰੋ", uncertainValues: "ਮੁੱਲ ਜਾਂਚਣੇ ਹਨ", fieldTest: "ਟੈਸਟ", fieldValue: "ਮੁੱਲ", fieldUnit: "ਇਕਾਈ" },
  or: { reviewTitle: "ଅସ୍ପଷ୍ଟ ମୂଲ୍ୟ ଯାଞ୍ଚ କରନ୍ତୁ", reviewIntro: "ଚିହ୍ନିତ ଲେଖା ପଢ଼ିବା କଷ୍ଟକର ଥିଲା। ରିପୋର୍ଟ ସହ ମେଳ କରି ଭୁଲ ସୁଧାରନ୍ତୁ।", confidence: "ବିଶ୍ୱାସ", highConfidence: "ସ୍ପଷ୍ଟ", mediumConfidence: "ଯାଞ୍ଚ", lowConfidence: "ଅସ୍ପଷ୍ଟ", confirmValues: "ନିଶ୍ଚିତ କରି ବୁଝାନ୍ତୁ", cancelReview: "ବାତିଲ", uncertainValues: "ମୂଲ୍ୟ ଯାଞ୍ଚ ଆବଶ୍ୟକ", fieldTest: "ପରୀକ୍ଷା", fieldValue: "ମୂଲ୍ୟ", fieldUnit: "ଏକକ" },
  ur: { reviewTitle: "غیر واضح اقدار چیک کریں", reviewIntro: "نشان زدہ متن پڑھنا مشکل تھا۔ رپورٹ سے موازنہ کریں اور وضاحت سے پہلے غلطی درست کریں۔", confidence: "اعتماد", highConfidence: "واضح", mediumConfidence: "چیک کریں", lowConfidence: "غیر واضح", confirmValues: "تصدیق کرکے سمجھائیں", cancelReview: "منسوخ", uncertainValues: "اقدار چیک کرنا ضروری ہیں", fieldTest: "ٹیسٹ", fieldValue: "قدر", fieldUnit: "اکائی" }
};

const featureTranslations = {
  en: { overview:"Overview",nextSteps:"Next steps",chooseLanguage:"Choose language",close:"Close",all:"All",outsideRange:"Outside range",uncertain:"Uncertain",confirmed:"Confirmed",summary:"Results overview",attention:"Needs attention",trends:"Local trends",noTrends:"Add another matching report to see a trend.",date:"Date",glossary:"Medical terms",readAloud:"Read aloud",stopReading:"Stop reading",speechUnavailable:"Read aloud is not available for this language on this device.",doctorSummary:"Doctor visit summary",followUpReminder:"Follow-up reminder",reminderDate:"Reminder date",addToCalendar:"Add to calendar",selectDate:"Choose a reminder date first.",rangePosition:"Position within the report range",trendTable:"Trend values",visitToolkit:"Visit toolkit" },
  hi: { overview:"सारांश",nextSteps:"अगले कदम",chooseLanguage:"भाषा चुनें",close:"बंद करें",all:"सभी",outsideRange:"सीमा से बाहर",uncertain:"अनिश्चित",confirmed:"पुष्ट",summary:"परिणाम सारांश",attention:"ध्यान आवश्यक",trends:"स्थानीय रुझान",noTrends:"रुझान देखने के लिए दूसरी मिलती-जुलती रिपोर्ट जोड़ें।",date:"तारीख",glossary:"चिकित्सा शब्द",readAloud:"सुनें",stopReading:"पढ़ना रोकें",speechUnavailable:"इस डिवाइस पर इस भाषा में सुनाने की सुविधा उपलब्ध नहीं है।",doctorSummary:"डॉक्टर मुलाकात सारांश",followUpReminder:"फॉलो-अप रिमाइंडर",reminderDate:"रिमाइंडर की तारीख",addToCalendar:"कैलेंडर में जोड़ें",selectDate:"पहले रिमाइंडर की तारीख चुनें।",rangePosition:"रिपोर्ट की सीमा में स्थिति",trendTable:"रुझान मान",visitToolkit:"मुलाकात टूलकिट" },
  bn: { overview:"সারাংশ",nextSteps:"পরবর্তী পদক্ষেপ",chooseLanguage:"ভাষা বেছে নিন",close:"বন্ধ করুন",all:"সব",outsideRange:"সীমার বাইরে",uncertain:"অনিশ্চিত",confirmed:"নিশ্চিত",summary:"ফলাফলের সারাংশ",attention:"মনোযোগ প্রয়োজন",trends:"স্থানীয় প্রবণতা",noTrends:"প্রবণতা দেখতে আরেকটি মিল থাকা রিপোর্ট যোগ করুন।",date:"তারিখ",glossary:"চিকিৎসা পরিভাষা",readAloud:"শুনুন",stopReading:"পড়া বন্ধ করুন",speechUnavailable:"এই ডিভাইসে এই ভাষায় পড়ে শোনানো যায় না।",doctorSummary:"ডাক্তার দেখানোর সারাংশ",followUpReminder:"ফলো-আপ স্মরণিকা",reminderDate:"স্মরণিকার তারিখ",addToCalendar:"ক্যালেন্ডারে যোগ করুন",selectDate:"প্রথমে স্মরণিকার তারিখ বেছে নিন।",rangePosition:"রিপোর্টের সীমায় অবস্থান",trendTable:"প্রবণতার মান",visitToolkit:"ভিজিট টুলকিট" },
  as: { overview:"সাৰাংশ",nextSteps:"পৰৱৰ্তী পদক্ষেপ",chooseLanguage:"ভাষা বাছক",close:"বন্ধ কৰক",all:"সকলো",outsideRange:"সীমাৰ বাহিৰত",uncertain:"অনিশ্চিত",confirmed:"নিশ্চিত",summary:"ফলাফলৰ সাৰাংশ",attention:"মনোযোগৰ প্ৰয়োজন",trends:"স্থানীয় ধাৰা",noTrends:"ধাৰা চাবলৈ আন এখন মিল থকা প্ৰতিবেদন যোগ কৰক।",date:"তাৰিখ",glossary:"চিকিৎসা শব্দ",readAloud:"শুনি লওক",stopReading:"পঢ়া বন্ধ কৰক",speechUnavailable:"এই ডিভাইচত এই ভাষাৰ পঢ়ি শুনোৱা সুবিধা নাই।",doctorSummary:"চিকিৎসক সাক্ষাতৰ সাৰাংশ",followUpReminder:"ফলো-আপ সোঁৱৰণী",reminderDate:"সোঁৱৰণীৰ তাৰিখ",addToCalendar:"কেলেণ্ডাৰত যোগ কৰক",selectDate:"আগতে সোঁৱৰণীৰ তাৰিখ বাছক।",rangePosition:"প্ৰতিবেদনৰ সীমাত অৱস্থান",trendTable:"ধাৰাৰ মান",visitToolkit:"সাক্ষাৎ সঁজুলি" },
  ta: { overview:"மேலோட்டம்",nextSteps:"அடுத்த படிகள்",chooseLanguage:"மொழியைத் தேர்ந்தெடுக்கவும்",close:"மூடு",all:"அனைத்தும்",outsideRange:"வரம்பிற்கு வெளியே",uncertain:"உறுதியற்றது",confirmed:"உறுதிசெய்யப்பட்டது",summary:"முடிவுகளின் சுருக்கம்",attention:"கவனம் தேவை",trends:"உள்ளூர் போக்குகள்",noTrends:"போக்கைக் காண பொருந்தும் மற்றொரு அறிக்கையைச் சேர்க்கவும்.",date:"தேதி",glossary:"மருத்துவச் சொற்கள்",readAloud:"வாசிக்கவும்",stopReading:"வாசிப்பை நிறுத்தவும்",speechUnavailable:"இந்தச் சாதனத்தில் இந்த மொழிக்கான வாசிப்பு வசதி இல்லை.",doctorSummary:"மருத்துவர் சந்திப்பு சுருக்கம்",followUpReminder:"தொடர் நினைவூட்டல்",reminderDate:"நினைவூட்டல் தேதி",addToCalendar:"நாள்காட்டியில் சேர்",selectDate:"முதலில் நினைவூட்டல் தேதியைத் தேர்ந்தெடுக்கவும்.",rangePosition:"அறிக்கை வரம்பில் நிலை",trendTable:"போக்கு மதிப்புகள்",visitToolkit:"சந்திப்பு கருவிகள்" },
  te: { overview:"సారాంశం",nextSteps:"తదుపరి చర్యలు",chooseLanguage:"భాషను ఎంచుకోండి",close:"మూసివేయి",all:"అన్నీ",outsideRange:"పరిధి బయట",uncertain:"అనిశ్చితం",confirmed:"నిర్ధారితం",summary:"ఫలితాల సారాంశం",attention:"శ్రద్ధ అవసరం",trends:"స్థానిక ధోరణులు",noTrends:"ధోరణి చూడటానికి సరిపోలే మరో నివేదికను జోడించండి.",date:"తేదీ",glossary:"వైద్య పదాలు",readAloud:"చదివి వినిపించు",stopReading:"చదవడం ఆపు",speechUnavailable:"ఈ పరికరంలో ఈ భాషకు చదివి వినిపించడం అందుబాటులో లేదు.",doctorSummary:"వైద్యుని సందర్శన సారాంశం",followUpReminder:"ఫాలో-అప్ గుర్తుచేయింపు",reminderDate:"గుర్తుచేయింపు తేదీ",addToCalendar:"క్యాలెండర్‌కు జోడించు",selectDate:"ముందుగా గుర్తుచేయింపు తేదీని ఎంచుకోండి.",rangePosition:"నివేదిక పరిధిలో స్థానం",trendTable:"ధోరణి విలువలు",visitToolkit:"సందర్శన సాధనాలు" },
  mr: { overview:"आढावा",nextSteps:"पुढील पावले",chooseLanguage:"भाषा निवडा",close:"बंद करा",all:"सर्व",outsideRange:"मर्यादेबाहेर",uncertain:"अनिश्चित",confirmed:"पुष्टी केलेले",summary:"निकालांचा आढावा",attention:"लक्ष आवश्यक",trends:"स्थानिक कल",noTrends:"कल पाहण्यासाठी आणखी एक जुळणारा अहवाल जोडा.",date:"तारीख",glossary:"वैद्यकीय संज्ञा",readAloud:"मोठ्याने वाचा",stopReading:"वाचन थांबवा",speechUnavailable:"या उपकरणावर या भाषेसाठी वाचन उपलब्ध नाही.",doctorSummary:"डॉक्टर भेट सारांश",followUpReminder:"पाठपुरावा स्मरणपत्र",reminderDate:"स्मरणपत्राची तारीख",addToCalendar:"कॅलेंडरमध्ये जोडा",selectDate:"आधी स्मरणपत्राची तारीख निवडा.",rangePosition:"अहवालाच्या मर्यादेतील स्थान",trendTable:"कल मूल्ये",visitToolkit:"भेट साधने" },
  kn: { overview:"ಅವಲೋಕನ",nextSteps:"ಮುಂದಿನ ಕ್ರಮಗಳು",chooseLanguage:"ಭಾಷೆ ಆಯ್ಕೆಮಾಡಿ",close:"ಮುಚ್ಚಿ",all:"ಎಲ್ಲಾ",outsideRange:"ವ್ಯಾಪ್ತಿಯ ಹೊರಗೆ",uncertain:"ಅನಿಶ್ಚಿತ",confirmed:"ದೃಢೀಕೃತ",summary:"ಫಲಿತಾಂಶಗಳ ಅವಲೋಕನ",attention:"ಗಮನ ಅಗತ್ಯ",trends:"ಸ್ಥಳೀಯ ಪ್ರವೃತ್ತಿಗಳು",noTrends:"ಪ್ರವೃತ್ತಿ ನೋಡಲು ಹೊಂದುವ ಇನ್ನೊಂದು ವರದಿಯನ್ನು ಸೇರಿಸಿ.",date:"ದಿನಾಂಕ",glossary:"ವೈದ್ಯಕೀಯ ಪದಗಳು",readAloud:"ಓದಿ ಕೇಳಿಸಿ",stopReading:"ಓದುವುದನ್ನು ನಿಲ್ಲಿಸಿ",speechUnavailable:"ಈ ಸಾಧನದಲ್ಲಿ ಈ ಭಾಷೆಗೆ ಓದಿ ಕೇಳಿಸುವ ಸೌಲಭ್ಯವಿಲ್ಲ.",doctorSummary:"ವೈದ್ಯರ ಭೇಟಿ ಸಾರಾಂಶ",followUpReminder:"ಫಾಲೋ-ಅಪ್ ಜ್ಞಾಪನೆ",reminderDate:"ಜ್ಞಾಪನೆ ದಿನಾಂಕ",addToCalendar:"ಕ್ಯಾಲೆಂಡರ್‌ಗೆ ಸೇರಿಸಿ",selectDate:"ಮೊದಲು ಜ್ಞಾಪನೆ ದಿನಾಂಕ ಆಯ್ಕೆಮಾಡಿ.",rangePosition:"ವರದಿ ವ್ಯಾಪ್ತಿಯಲ್ಲಿನ ಸ್ಥಾನ",trendTable:"ಪ್ರವೃತ್ತಿ ಮೌಲ್ಯಗಳು",visitToolkit:"ಭೇಟಿ ಸಾಧನಗಳು" },
  gu: { overview:"સારાંશ",nextSteps:"આગળનાં પગલાં",chooseLanguage:"ભાષા પસંદ કરો",close:"બંધ કરો",all:"બધા",outsideRange:"મર્યાદાની બહાર",uncertain:"અનિશ્ચિત",confirmed:"ખાતરી કરેલ",summary:"પરિણામોનો સારાંશ",attention:"ધ્યાન જરૂરી",trends:"સ્થાનિક વલણો",noTrends:"વલણ જોવા બીજી મેળ ખાતી રિપોર્ટ ઉમેરો.",date:"તારીખ",glossary:"તબીબી શબ્દો",readAloud:"વાંચી સંભળાવો",stopReading:"વાંચવાનું રોકો",speechUnavailable:"આ ઉપકરણ પર આ ભાષામાં વાંચી સંભળાવવું ઉપલબ્ધ નથી.",doctorSummary:"ડૉક્ટર મુલાકાત સારાંશ",followUpReminder:"ફોલો-અપ રિમાઇન્ડર",reminderDate:"રિમાઇન્ડરની તારીખ",addToCalendar:"કૅલેન્ડરમાં ઉમેરો",selectDate:"પહેલાં રિમાઇન્ડરની તારીખ પસંદ કરો.",rangePosition:"રિપોર્ટની મર્યાદામાં સ્થાન",trendTable:"વલણ મૂલ્યો",visitToolkit:"મુલાકાત સાધનો" },
  ml: { overview:"അവലോകനം",nextSteps:"അടുത്ത ഘട്ടങ്ങൾ",chooseLanguage:"ഭാഷ തിരഞ്ഞെടുക്കുക",close:"അടയ്ക്കുക",all:"എല്ലാം",outsideRange:"പരിധിക്ക് പുറത്ത്",uncertain:"അനിശ്ചിതം",confirmed:"സ്ഥിരീകരിച്ചത്",summary:"ഫലങ്ങളുടെ അവലോകനം",attention:"ശ്രദ്ധ ആവശ്യമാണ്",trends:"പ്രാദേശിക പ്രവണതകൾ",noTrends:"പ്രവണത കാണാൻ പൊരുത്തപ്പെടുന്ന മറ്റൊരു റിപ്പോർട്ട് ചേർക്കുക.",date:"തീയതി",glossary:"മെഡിക്കൽ പദങ്ങൾ",readAloud:"വായിച്ചു കേൾപ്പിക്കുക",stopReading:"വായന നിർത്തുക",speechUnavailable:"ഈ ഉപകരണത്തിൽ ഈ ഭാഷയ്ക്കുള്ള വായന ലഭ്യമല്ല.",doctorSummary:"ഡോക്ടർ സന്ദർശന സംഗ്രഹം",followUpReminder:"ഫോളോ-അപ്പ് ഓർമ്മപ്പെടുത്തൽ",reminderDate:"ഓർമ്മപ്പെടുത്തൽ തീയതി",addToCalendar:"കലണ്ടറിൽ ചേർക്കുക",selectDate:"ആദ്യം ഓർമ്മപ്പെടുത്തൽ തീയതി തിരഞ്ഞെടുക്കുക.",rangePosition:"റിപ്പോർട്ട് പരിധിയിലെ സ്ഥാനം",trendTable:"പ്രവണതാ മൂല്യങ്ങൾ",visitToolkit:"സന്ദർശന ഉപകരണങ്ങൾ" },
  pa: { overview:"ਸੰਖੇਪ",nextSteps:"ਅਗਲੇ ਕਦਮ",chooseLanguage:"ਭਾਸ਼ਾ ਚੁਣੋ",close:"ਬੰਦ ਕਰੋ",all:"ਸਾਰੇ",outsideRange:"ਸੀਮਾ ਤੋਂ ਬਾਹਰ",uncertain:"ਅਨਿਸ਼ਚਿਤ",confirmed:"ਪੁਸ਼ਟੀ ਕੀਤੀ",summary:"ਨਤੀਜਿਆਂ ਦਾ ਸੰਖੇਪ",attention:"ਧਿਆਨ ਦੀ ਲੋੜ",trends:"ਸਥਾਨਕ ਰੁਝਾਨ",noTrends:"ਰੁਝਾਨ ਵੇਖਣ ਲਈ ਇੱਕ ਹੋਰ ਮਿਲਦੀ ਰਿਪੋਰਟ ਜੋੜੋ।",date:"ਤਾਰੀਖ",glossary:"ਮੈਡੀਕਲ ਸ਼ਬਦ",readAloud:"ਪੜ੍ਹ ਕੇ ਸੁਣਾਓ",stopReading:"ਪੜ੍ਹਨਾ ਰੋਕੋ",speechUnavailable:"ਇਸ ਡਿਵਾਈਸ ਉੱਤੇ ਇਸ ਭਾਸ਼ਾ ਲਈ ਪੜ੍ਹ ਕੇ ਸੁਣਾਉਣਾ ਉਪਲਬਧ ਨਹੀਂ।",doctorSummary:"ਡਾਕਟਰ ਮੁਲਾਕਾਤ ਸੰਖੇਪ",followUpReminder:"ਫਾਲੋ-ਅਪ ਯਾਦਦਿਹਾਨੀ",reminderDate:"ਯਾਦਦਿਹਾਨੀ ਦੀ ਤਾਰੀਖ",addToCalendar:"ਕੈਲੰਡਰ ਵਿੱਚ ਜੋੜੋ",selectDate:"ਪਹਿਲਾਂ ਯਾਦਦਿਹਾਨੀ ਦੀ ਤਾਰੀਖ ਚੁਣੋ।",rangePosition:"ਰਿਪੋਰਟ ਦੀ ਸੀਮਾ ਵਿੱਚ ਸਥਿਤੀ",trendTable:"ਰੁਝਾਨ ਮੁੱਲ",visitToolkit:"ਮੁਲਾਕਾਤ ਸੰਦ" },
  or: { overview:"ସାରାଂଶ",nextSteps:"ପରବର୍ତ୍ତୀ ପଦକ୍ଷେପ",chooseLanguage:"ଭାଷା ବାଛନ୍ତୁ",close:"ବନ୍ଦ କରନ୍ତୁ",all:"ସବୁ",outsideRange:"ସୀମା ବାହାରେ",uncertain:"ଅନିଶ୍ଚିତ",confirmed:"ନିଶ୍ଚିତ",summary:"ଫଳାଫଳ ସାରାଂଶ",attention:"ଧ୍ୟାନ ଆବଶ୍ୟକ",trends:"ସ୍ଥାନୀୟ ଧାରା",noTrends:"ଧାରା ଦେଖିବାକୁ ଆଉ ଏକ ମେଳ ଥିବା ରିପୋର୍ଟ ଯୋଡ଼ନ୍ତୁ।",date:"ତାରିଖ",glossary:"ଚିକିତ୍ସା ଶବ୍ଦ",readAloud:"ପଢ଼ି ଶୁଣାନ୍ତୁ",stopReading:"ପଢ଼ା ବନ୍ଦ କରନ୍ତୁ",speechUnavailable:"ଏହି ଡିଭାଇସରେ ଏହି ଭାଷା ପାଇଁ ପଢ଼ି ଶୁଣାଇବା ସୁବିଧା ନାହିଁ।",doctorSummary:"ଡାକ୍ତର ସାକ୍ଷାତ ସାରାଂଶ",followUpReminder:"ଫଲୋ-ଅପ୍ ସ୍ମାରକ",reminderDate:"ସ୍ମାରକ ତାରିଖ",addToCalendar:"କ୍ୟାଲେଣ୍ଡରରେ ଯୋଡ଼ନ୍ତୁ",selectDate:"ପ୍ରଥମେ ସ୍ମାରକ ତାରିଖ ବାଛନ୍ତୁ।",rangePosition:"ରିପୋର୍ଟ ସୀମାରେ ସ୍ଥିତି",trendTable:"ଧାରା ମୂଲ୍ୟ",visitToolkit:"ସାକ୍ଷାତ ସାଧନ" },
  ur: { overview:"خلاصہ",nextSteps:"اگلے اقدامات",chooseLanguage:"زبان منتخب کریں",close:"بند کریں",all:"سب",outsideRange:"حد سے باہر",uncertain:"غیر یقینی",confirmed:"تصدیق شدہ",summary:"نتائج کا خلاصہ",attention:"توجہ درکار",trends:"مقامی رجحانات",noTrends:"رجحان دیکھنے کے لیے ایک اور مماثل رپورٹ شامل کریں۔",date:"تاریخ",glossary:"طبی اصطلاحات",readAloud:"سنیں",stopReading:"پڑھنا روکیں",speechUnavailable:"اس آلے پر اس زبان میں پڑھ کر سنانے کی سہولت دستیاب نہیں۔",doctorSummary:"ڈاکٹر ملاقات کا خلاصہ",followUpReminder:"فالو اپ یاد دہانی",reminderDate:"یاد دہانی کی تاریخ",addToCalendar:"کیلنڈر میں شامل کریں",selectDate:"پہلے یاد دہانی کی تاریخ منتخب کریں۔",rangePosition:"رپورٹ کی حد میں مقام",trendTable:"رجحان کی اقدار",visitToolkit:"ملاقات کے اوزار" }
};

const errorTranslations = {
  en: { requestFailed: "Something went wrong. Please try again.", analysisTimeout: "The analysis is taking longer than expected. Please try again." },
  hi: { requestFailed: "कुछ गलत हुआ। कृपया फिर से कोशिश करें।" },
  bn: { requestFailed: "কিছু ভুল হয়েছে। আবার চেষ্টা করুন।" },
  as: { requestFailed: "কিবা ভুল হৈছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।", analysisTimeout: "বিশ্লেষণত আশা কৰাতকৈ বেছি সময় লাগিছে। অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।" },
  ta: { requestFailed: "ஏதோ தவறு ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்." },
  te: { requestFailed: "ఏదో తప్పు జరిగింది. దయచేసి మళ్లీ ప్రయత్నించండి." },
  mr: { requestFailed: "काहीतरी चूक झाली. कृपया पुन्हा प्रयत्न करा." },
  kn: { requestFailed: "ಏನೋ ತಪ್ಪಾಗಿದೆ. ದಯವಿಟ್ಟು ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ." },
  gu: { requestFailed: "કંઈક ખોટું થયું. કૃપા કરીને ફરી પ્રયાસ કરો." },
  ml: { requestFailed: "എന്തോ പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക." },
  pa: { requestFailed: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ। ਕਿਰਪਾ ਕਰਕੇ ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।" },
  or: { requestFailed: "କିଛି ଭୁଲ ହୋଇଛି। ଦୟାକରି ପୁଣି ଚେଷ୍ଟା କରନ୍ତୁ।" },
  ur: { requestFailed: "کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔" }
};

const experienceTranslations = {
  en: { uninterpreted:"Not interpreted — compare with your original report.",expandAll:"Expand all",collapseAll:"Collapse all",needsAttention:"Needs attention",audioConsent:"To create natural narration, Lumen sends this report explanation text to Microsoft Azure. No report image is sent. Allow this on this device?",audioDisclosure:"The voice is AI-generated.",audioLoading:"Preparing audio…",playAudio:"Play",pauseAudio:"Pause",restartAudio:"Restart",tooManyFindings:"This report contains too many results to show safely. Upload fewer pages." },
  hi: { uninterpreted:"व्याख्या नहीं हुई — अपनी मूल रिपोर्ट से मिलाएँ।",expandAll:"सभी खोलें",collapseAll:"सभी बंद करें",needsAttention:"ध्यान आवश्यक",audioConsent:"स्वाभाविक ऑडियो बनाने के लिए Lumen इस रिपोर्ट की व्याख्या का पाठ Microsoft Azure को भेजता है। रिपोर्ट की छवि नहीं भेजी जाती। इस डिवाइस पर अनुमति दें?",audioDisclosure:"यह आवाज़ AI द्वारा बनाई गई है।",audioLoading:"ऑडियो तैयार हो रहा है…",playAudio:"चलाएँ",pauseAudio:"रोकें",restartAudio:"फिर से चलाएँ",tooManyFindings:"इस रिपोर्ट में सुरक्षित रूप से दिखाने के लिए बहुत अधिक परिणाम हैं। कम पृष्ठ अपलोड करें।" },
  bn: { uninterpreted:"ব্যাখ্যা করা যায়নি — মূল রিপোর্টের সঙ্গে মিলিয়ে দেখুন।",expandAll:"সব খুলুন",collapseAll:"সব বন্ধ করুন",needsAttention:"মনোযোগ প্রয়োজন",audioConsent:"স্বাভাবিক অডিও তৈরির জন্য Lumen এই রিপোর্টের ব্যাখ্যার লেখা Microsoft Azure-এ পাঠায়। রিপোর্টের ছবি পাঠানো হয় না। এই ডিভাইসে অনুমতি দেবেন?",audioDisclosure:"কণ্ঠটি AI দ্বারা তৈরি।",audioLoading:"অডিও প্রস্তুত হচ্ছে…",playAudio:"চালান",pauseAudio:"বিরতি",restartAudio:"আবার চালান",tooManyFindings:"এই রিপোর্টে নিরাপদে দেখানোর জন্য অনেক বেশি ফলাফল রয়েছে। কম পৃষ্ঠা আপলোড করুন।" },
  as: { uninterpreted:"ব্যাখ্যা কৰা হোৱা নাই — মূল প্ৰতিবেদনৰ সৈতে মিলাওক।",expandAll:"সকলো খোলক",collapseAll:"সকলো বন্ধ কৰক",needsAttention:"মনোযোগৰ প্ৰয়োজন",audioConsent:"স্বাভাৱিক অডিঅ'ৰ বাবে Lumen-এ এই ব্যাখ্যাৰ পাঠ Microsoft Azure-লৈ পঠিয়ায়। প্ৰতিবেদনৰ ছবি পঠোৱা নহয়। অনুমতি দিবনে?",audioDisclosure:"কণ্ঠটো AI-এ সৃষ্টি কৰা।",audioLoading:"অডিঅ' প্ৰস্তুত হৈছে…",playAudio:"চলাওক",pauseAudio:"বিৰতি",restartAudio:"পুনৰ চলাওক",tooManyFindings:"এই প্ৰতিবেদনত সুৰক্ষিতভাৱে দেখুৱাবলৈ অত্যধিক ফলাফল আছে। কম পৃষ্ঠা আপলোড কৰক।" },
  ta: { uninterpreted:"விளக்கப்படவில்லை — அசல் அறிக்கையுடன் ஒப்பிடவும்.",expandAll:"அனைத்தையும் விரிக்கவும்",collapseAll:"அனைத்தையும் சுருக்கவும்",needsAttention:"கவனம் தேவை",audioConsent:"இயல்பான ஒலிக்காக இந்த அறிக்கை விளக்க உரையை Lumen Microsoft Azure-க்கு அனுப்பும். அறிக்கை படம் அனுப்பப்படாது. அனுமதிக்கவா?",audioDisclosure:"இந்தக் குரல் AI உருவாக்கியது.",audioLoading:"ஒலி தயாராகிறது…",playAudio:"இயக்கு",pauseAudio:"இடைநிறுத்து",restartAudio:"மீண்டும் இயக்கு",tooManyFindings:"பாதுகாப்பாகக் காட்ட முடியாத அளவு முடிவுகள் உள்ளன. குறைவான பக்கங்களைப் பதிவேற்றவும்." },
  te: { uninterpreted:"వివరించబడలేదు — అసలు నివేదికతో పోల్చండి.",expandAll:"అన్నీ తెరవండి",collapseAll:"అన్నీ మూసివేయండి",needsAttention:"శ్రద్ధ అవసరం",audioConsent:"సహజ ఆడియో కోసం Lumen ఈ వివరణ పాఠాన్ని Microsoft Azureకు పంపుతుంది. నివేదిక చిత్రం పంపబడదు. అనుమతించాలా?",audioDisclosure:"ఈ స్వరం AI రూపొందించింది.",audioLoading:"ఆడియో సిద్ధమవుతోంది…",playAudio:"ప్లే",pauseAudio:"విరామం",restartAudio:"మళ్లీ ప్లే",tooManyFindings:"సురక్షితంగా చూపడానికి ఈ నివేదికలో చాలా ఫలితాలు ఉన్నాయి. తక్కువ పేజీలు అప్‌లోడ్ చేయండి." },
  mr: { uninterpreted:"स्पष्टीकरण झाले नाही — मूळ अहवालाशी तुलना करा.",expandAll:"सर्व उघडा",collapseAll:"सर्व बंद करा",needsAttention:"लक्ष आवश्यक",audioConsent:"नैसर्गिक ऑडिओसाठी Lumen या स्पष्टीकरणाचा मजकूर Microsoft Azure कडे पाठवते. अहवालाचे चित्र पाठवले जात नाही. परवानगी द्यायची?",audioDisclosure:"हा आवाज AI ने तयार केला आहे.",audioLoading:"ऑडिओ तयार होत आहे…",playAudio:"चालू करा",pauseAudio:"थांबवा",restartAudio:"पुन्हा चालू करा",tooManyFindings:"या अहवालात सुरक्षितपणे दाखवण्यासाठी खूप निकाल आहेत. कमी पाने अपलोड करा." },
  kn: { uninterpreted:"ವಿವರಿಸಲಾಗಿಲ್ಲ — ಮೂಲ ವರದಿಯೊಂದಿಗೆ ಹೋಲಿಸಿ.",expandAll:"ಎಲ್ಲವನ್ನೂ ತೆರೆಯಿರಿ",collapseAll:"ಎಲ್ಲವನ್ನೂ ಮುಚ್ಚಿರಿ",needsAttention:"ಗಮನ ಅಗತ್ಯ",audioConsent:"ಸಹಜ ಧ್ವನಿಗಾಗಿ Lumen ಈ ವಿವರಣೆಯ ಪಠ್ಯವನ್ನು Microsoft Azureಗೆ ಕಳುಹಿಸುತ್ತದೆ. ವರದಿ ಚಿತ್ರವನ್ನು ಕಳುಹಿಸುವುದಿಲ್ಲ. ಅನುಮತಿಸುವಿರಾ?",audioDisclosure:"ಈ ಧ್ವನಿ AI ರಚಿಸಿದೆ.",audioLoading:"ಧ್ವನಿ ಸಿದ್ಧವಾಗುತ್ತಿದೆ…",playAudio:"ಪ್ಲೇ",pauseAudio:"ವಿರಾಮ",restartAudio:"ಮತ್ತೆ ಪ್ಲೇ",tooManyFindings:"ಸುರಕ್ಷಿತವಾಗಿ ತೋರಿಸಲು ಈ ವರದಿಯಲ್ಲಿ ಹೆಚ್ಚು ಫಲಿತಾಂಶಗಳಿವೆ. ಕಡಿಮೆ ಪುಟಗಳನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ." },
  gu: { uninterpreted:"સમજાવવામાં આવ્યું નથી — મૂળ રિપોર્ટ સાથે સરખાવો.",expandAll:"બધું ખોલો",collapseAll:"બધું બંધ કરો",needsAttention:"ધ્યાન જરૂરી",audioConsent:"કુદરતી ઓડિયો માટે Lumen આ સમજાવટનો લખાણ Microsoft Azureને મોકલે છે. રિપોર્ટનું ચિત્ર મોકલાતું નથી. મંજૂરી આપશો?",audioDisclosure:"આ અવાજ AI દ્વારા બનાવેલો છે.",audioLoading:"ઓડિયો તૈયાર થઈ રહ્યો છે…",playAudio:"ચાલુ કરો",pauseAudio:"વિરામ",restartAudio:"ફરી ચલાવો",tooManyFindings:"આ રિપોર્ટમાં સુરક્ષિત રીતે બતાવવા માટે ઘણા પરિણામો છે. ઓછા પાનાં અપલોડ કરો." },
  ml: { uninterpreted:"വിശദീകരിച്ചിട്ടില്ല — യഥാർത്ഥ റിപ്പോർട്ടുമായി താരതമ്യം ചെയ്യുക.",expandAll:"എല്ലാം തുറക്കുക",collapseAll:"എല്ലാം അടയ്ക്കുക",needsAttention:"ശ്രദ്ധ ആവശ്യമാണ്",audioConsent:"സ്വാഭാവിക ശബ്ദത്തിനായി Lumen ഈ വിശദീകരണ വാചകം Microsoft Azure-ലേക്ക് അയയ്ക്കുന്നു. റിപ്പോർട്ട് ചിത്രം അയയ്ക്കില്ല. അനുവദിക്കണോ?",audioDisclosure:"ഈ ശബ്ദം AI സൃഷ്ടിച്ചതാണ്.",audioLoading:"ഓഡിയോ തയ്യാറാക്കുന്നു…",playAudio:"പ്ലേ",pauseAudio:"താൽക്കാലികമായി നിർത്തുക",restartAudio:"വീണ്ടും പ്ലേ",tooManyFindings:"സുരക്ഷിതമായി കാണിക്കാനാവാത്തത്ര ഫലങ്ങൾ റിപ്പോർട്ടിലുണ്ട്. കുറച്ച് പേജുകൾ അപ്‌ലോഡ് ചെയ്യുക." },
  pa: { uninterpreted:"ਵਿਆਖਿਆ ਨਹੀਂ ਕੀਤੀ ਗਈ — ਅਸਲ ਰਿਪੋਰਟ ਨਾਲ ਮਿਲਾਓ।",expandAll:"ਸਾਰੇ ਖੋਲ੍ਹੋ",collapseAll:"ਸਾਰੇ ਬੰਦ ਕਰੋ",needsAttention:"ਧਿਆਨ ਦੀ ਲੋੜ",audioConsent:"ਕੁਦਰਤੀ ਆਡੀਓ ਲਈ Lumen ਇਸ ਵਿਆਖਿਆ ਦਾ ਪਾਠ Microsoft Azure ਨੂੰ ਭੇਜਦਾ ਹੈ। ਰਿਪੋਰਟ ਦੀ ਤਸਵੀਰ ਨਹੀਂ ਭੇਜੀ ਜਾਂਦੀ। ਇਜਾਜ਼ਤ ਦੇਣੀ ਹੈ?",audioDisclosure:"ਇਹ ਆਵਾਜ਼ AI ਦੁਆਰਾ ਬਣਾਈ ਗਈ ਹੈ।",audioLoading:"ਆਡੀਓ ਤਿਆਰ ਹੋ ਰਿਹਾ ਹੈ…",playAudio:"ਚਲਾਓ",pauseAudio:"ਵਿਰਾਮ",restartAudio:"ਮੁੜ ਚਲਾਓ",tooManyFindings:"ਇਸ ਰਿਪੋਰਟ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਦਿਖਾਉਣ ਲਈ ਬਹੁਤ ਨਤੀਜੇ ਹਨ। ਘੱਟ ਪੰਨੇ ਅਪਲੋਡ ਕਰੋ।" },
  or: { uninterpreted:"ବ୍ୟାଖ୍ୟା ହୋଇନାହିଁ — ମୂଳ ରିପୋର୍ଟ ସହ ମେଳ କରନ୍ତୁ।",expandAll:"ସବୁ ଖୋଲନ୍ତୁ",collapseAll:"ସବୁ ବନ୍ଦ କରନ୍ତୁ",needsAttention:"ଧ୍ୟାନ ଆବଶ୍ୟକ",audioConsent:"ସ୍ୱାଭାବିକ ଅଡିଓ ପାଇଁ Lumen ଏହି ବ୍ୟାଖ୍ୟା ପାଠ Microsoft Azureକୁ ପଠାଏ। ରିପୋର୍ଟ ଛବି ପଠାଯାଏ ନାହିଁ। ଅନୁମତି ଦେବେ?",audioDisclosure:"ଏହି ସ୍ୱର AI ଦ୍ୱାରା ତିଆରି।",audioLoading:"ଅଡିଓ ପ୍ରସ୍ତୁତ ହେଉଛି…",playAudio:"ଚଲାନ୍ତୁ",pauseAudio:"ବିରତି",restartAudio:"ପୁଣି ଚଲାନ୍ତୁ",tooManyFindings:"ସୁରକ୍ଷିତ ଭାବରେ ଦେଖାଇବା ପାଇଁ ଅତ୍ୟଧିକ ଫଳ ଅଛି। କମ୍ ପୃଷ୍ଠା ଅପଲୋଡ୍ କରନ୍ତୁ।" },
  ur: { uninterpreted:"وضاحت نہیں کی گئی — اصل رپورٹ سے موازنہ کریں۔",expandAll:"سب کھولیں",collapseAll:"سب بند کریں",needsAttention:"توجہ درکار",audioConsent:"قدرتی آڈیو کے لیے Lumen اس وضاحت کا متن Microsoft Azure کو بھیجتا ہے۔ رپورٹ کی تصویر نہیں بھیجی جاتی۔ اجازت دیں؟",audioDisclosure:"یہ آواز AI سے بنائی گئی ہے۔",audioLoading:"آڈیو تیار ہو رہی ہے…",playAudio:"چلائیں",pauseAudio:"وقفہ",restartAudio:"دوبارہ چلائیں",tooManyFindings:"اس رپورٹ میں محفوظ طور پر دکھانے کے لیے بہت زیادہ نتائج ہیں۔ کم صفحات اپ لوڈ کریں۔" }
};

const europeanTranslations = {
  es: { heroTitle:"Tu informe médico,",heroEmphasis:"por fin en palabras sencillas.",heroBody:"Sube un informe o una receta. Lumen explica cada valor y prepara preguntas para tu médico.",language:"Idioma",languages:"idiomas",explain:"Explicar mi informe",drop:"Suelta tu informe aquí",findings:"Tus resultados",meaning:"Qué significa",questions:"Preguntas para tu médico",changeLanguage:"Cambiar idioma",newReport:"Nuevo informe",normal:"Dentro del rango",low:"Bajo",high:"Alto",borderline:"Límite",critical:"Crítico",overview:"Resumen",nextSteps:"Siguientes pasos",chooseLanguage:"Elegir idioma",close:"Cerrar",all:"Todos",outsideRange:"Fuera del rango",uncertain:"Inciertos",confirmed:"Confirmados",attention:"Requiere atención",readAloud:"Escuchar",stopReading:"Detener",reference:"Referencia",report:"Informe" },
  fr: { heroTitle:"Votre compte rendu médical,",heroEmphasis:"enfin en termes simples.",heroBody:"Importez un bilan ou une ordonnance. Lumen explique chaque valeur et prépare vos questions.",language:"Langue",languages:"langues",explain:"Expliquer mon rapport",drop:"Déposez votre rapport ici",findings:"Vos résultats",meaning:"Ce que cela signifie",questions:"Questions au médecin",changeLanguage:"Changer de langue",newReport:"Nouveau rapport",normal:"Dans la plage",low:"Bas",high:"Élevé",borderline:"Limite",critical:"Critique",overview:"Aperçu",nextSteps:"Étapes suivantes",chooseLanguage:"Choisir la langue",close:"Fermer",all:"Tous",outsideRange:"Hors plage",uncertain:"Incertains",confirmed:"Confirmés",attention:"À surveiller",readAloud:"Écouter",stopReading:"Arrêter",reference:"Référence",report:"Rapport" },
  de: { heroTitle:"Ihr medizinischer Bericht,",heroEmphasis:"endlich einfach erklärt.",heroBody:"Laden Sie einen Laborbericht oder ein Rezept hoch. Lumen erklärt jeden Wert und bereitet Fragen vor.",language:"Sprache",languages:"Sprachen",explain:"Bericht erklären",drop:"Bericht hier ablegen",findings:"Ihre Ergebnisse",meaning:"Was das bedeutet",questions:"Fragen an den Arzt",changeLanguage:"Sprache ändern",newReport:"Neuer Bericht",normal:"Im Berichtsbereich",low:"Niedrig",high:"Hoch",borderline:"Grenzwertig",critical:"Kritisch",overview:"Überblick",nextSteps:"Nächste Schritte",chooseLanguage:"Sprache wählen",close:"Schließen",all:"Alle",outsideRange:"Außerhalb",uncertain:"Unsicher",confirmed:"Bestätigt",attention:"Beachtung nötig",readAloud:"Anhören",stopReading:"Stoppen",reference:"Referenz",report:"Bericht" },
  it: { heroTitle:"Il tuo referto medico,",heroEmphasis:"finalmente in parole semplici.",heroBody:"Carica un referto o una prescrizione. Lumen spiega ogni valore e prepara le domande.",language:"Lingua",languages:"lingue",explain:"Spiega il referto",drop:"Trascina qui il referto",findings:"I tuoi risultati",meaning:"Cosa significa",questions:"Domande per il medico",changeLanguage:"Cambia lingua",newReport:"Nuovo referto",normal:"Nell'intervallo",low:"Basso",high:"Alto",borderline:"Limite",critical:"Critico",overview:"Panoramica",nextSteps:"Prossimi passi",chooseLanguage:"Scegli lingua",close:"Chiudi",all:"Tutti",outsideRange:"Fuori intervallo",uncertain:"Incerto",confirmed:"Confermato",attention:"Richiede attenzione",readAloud:"Ascolta",stopReading:"Ferma",reference:"Riferimento",report:"Referto" },
  "pt-PT": { heroTitle:"O seu relatório médico,",heroEmphasis:"finalmente em palavras simples.",heroBody:"Carregue um relatório ou receita. O Lumen explica cada valor e prepara perguntas.",language:"Idioma",languages:"idiomas",explain:"Explicar o relatório",drop:"Largue o relatório aqui",findings:"Os seus resultados",meaning:"O que significa",questions:"Perguntas ao médico",changeLanguage:"Mudar idioma",newReport:"Novo relatório",normal:"Dentro do intervalo",low:"Baixo",high:"Alto",borderline:"Limite",critical:"Crítico",overview:"Visão geral",nextSteps:"Próximos passos",chooseLanguage:"Escolher idioma",close:"Fechar",all:"Todos",outsideRange:"Fora do intervalo",uncertain:"Incerto",confirmed:"Confirmado",attention:"Requer atenção",readAloud:"Ouvir",stopReading:"Parar",reference:"Referência",report:"Relatório" }
};

const releaseTranslations = {
  en: {
    processingConsentTitle: "Before Lumen analyses your report",
    processingConsentBody: "Your selected report pages and extracted text are sent securely to a configured AI provider to create the explanation. Lumen does not keep the report on its servers. You can withdraw this permission at any time.",
    processingConsentAccept: "Allow analysis",
    processingConsentDecline: "Not now",
    processingConsentManage: "Manage analysis consent",
    processingConsentDeclined: "Analysis was not started because permission was not granted.",
    beta: "Public beta"
  }
};

const metadata = [
  ["en", "English", "simple English", "ltr", "Latin", true],
  ["hi", "हिन्दी", "Hindi in Devanagari script", "ltr", "Devanagari", false],
  ["bn", "বাংলা", "Bengali in Bengali script", "ltr", "Bengali", false],
  ["as", "অসমীয়া", "Assamese in Bengali-Assamese script", "ltr", "Bengali", false],
  ["ta", "தமிழ்", "Tamil in Tamil script", "ltr", "Tamil", false],
  ["te", "తెలుగు", "Telugu in Telugu script", "ltr", "Telugu", false],
  ["mr", "मराठी", "Marathi in Devanagari script", "ltr", "Devanagari", false],
  ["kn", "ಕನ್ನಡ", "Kannada in Kannada script", "ltr", "Kannada", false],
  ["gu", "ગુજરાતી", "Gujarati in Gujarati script", "ltr", "Gujarati", false],
  ["ml", "മലയാളം", "Malayalam in Malayalam script", "ltr", "Malayalam", false],
  ["pa", "ਪੰਜਾਬੀ", "Punjabi in Gurmukhi script", "ltr", "Gurmukhi", false],
  ["or", "ଓଡ଼ିଆ", "Odia in Odia script", "ltr", "Odia", false],
  ["ur", "اردو", "Urdu in Arabic script", "rtl", "Arabic", false]
  ,["es", "Español", "Spanish in Latin script", "ltr", "Latin", false, false]
  ,["fr", "Français", "French in Latin script", "ltr", "Latin", false, false]
  ,["de", "Deutsch", "German in Latin script", "ltr", "Latin", false, false]
  ,["it", "Italiano", "Italian in Latin script", "ltr", "Latin", false, false]
  ,["pt-PT", "Português", "European Portuguese in Latin script", "ltr", "Latin", false, false]
];

export const LOCALES = metadata.map(([code, label, prompt, dir, script, _legacyReviewed, baseEnabled = true]) => {
  const ui = {
    ...en,
    ...reviewTranslations.en,
    ...featureTranslations.en,
    ...errorTranslations.en,
    ...(code === "en" ? en : translations[code]),
    ...europeanTranslations[code],
    ...reviewTranslations[code],
    ...featureTranslations[code],
    ...errorTranslations[code],
    ...(experienceTranslations[code] || experienceTranslations.en),
    ...(releaseTranslations[code] || releaseTranslations.en),
    ...TRANSLATION_OVERRIDES[code]
  };
  const storedReview = getReviewRecord(code);
  const reviewed = isReviewCurrent(code, ui, REQUIRED_UI_KEYS);
  const review = {
    ...storedReview,
    status: storedReview.status === "approved" && !reviewed ? "stale" : storedReview.status
  };
  return {
    code, label, prompt, dir, script, reviewed,
    enabled: baseEnabled || reviewed,
    review,
    ui
  };
});

export const DEFAULT_LOCALE = "en";

export function getLocale(code) {
  return LOCALES.find(locale => locale.code === code) || LOCALES[0];
}

export function getEnabledLocales({ reviewedOnly = false } = {}) {
  return LOCALES.filter(locale => locale.enabled && (!reviewedOnly || locale.reviewed));
}

export function isProductionLocale(value) {
  const code = typeof value === "string" ? value : value?.code;
  return LOCALES.some(locale => locale.code === code && locale.enabled && locale.reviewed);
}

export function getProductionLocales() {
  return LOCALES.filter(locale => isProductionLocale(locale));
}

export function translate(code, key) {
  const locale = getLocale(code);
  return locale.ui[key] || en[key] || key;
}

export function localeFromLegacyPrompt(prompt) {
  if (typeof prompt !== "string") return null;
  const legacyPrompts = {
    "simple English": "en",
    "Hindi (Devanagari script)": "hi",
    Bengali: "bn", Assamese: "as", Tamil: "ta", Telugu: "te", Marathi: "mr",
    Kannada: "kn", Gujarati: "gu", Malayalam: "ml",
    "Punjabi (Gurmukhi script)": "pa", Odia: "or", Urdu: "ur"
  };
  return LOCALES.find(locale => locale.prompt === prompt)?.code || legacyPrompts[prompt] || null;
}

const SCRIPT_PATTERNS = {
  Latin: /[A-Za-z]/gu,
  Devanagari: /[\u0900-\u097F]/gu,
  Bengali: /[\u0980-\u09FF]/gu,
  Gurmukhi: /[\u0A00-\u0A7F]/gu,
  Gujarati: /[\u0A80-\u0AFF]/gu,
  Odia: /[\u0B00-\u0B7F]/gu,
  Tamil: /[\u0B80-\u0BFF]/gu,
  Telugu: /[\u0C00-\u0C7F]/gu,
  Kannada: /[\u0C80-\u0CFF]/gu,
  Malayalam: /[\u0D00-\u0D7F]/gu,
  Arabic: /[\u0600-\u06FF\u0750-\u077F]/gu
};

export function hasExpectedScript(text, code) {
  const locale = getLocale(code);
  if (locale.code === "en") return true;
  const value = String(text || "");
  const letters = value.match(/\p{L}/gu) || [];
  const expected = value.match(SCRIPT_PATTERNS[locale.script]) || [];
  return expected.length >= 12 && expected.length / Math.max(letters.length, 1) >= 0.15;
}
